### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace
  commentId: T:ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace
  id: ISettingsSpace
  parent: ParmaGIS.Modules.Data.Space.Settings
  children:
  - ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace.Settings
  langs:
  - csharp
  - vb
  name: ISettingsSpace
  nameWithType: ISettingsSpace
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace
  type: Interface
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsSpace.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: ISettingsSpace
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsSpace.cs
    startLine: 5
  assemblies:
  - ParmaGIS.Modules.Data
  namespace: ParmaGIS.Modules.Data.Space.Settings
  summary: Представляет контракт взаимодействия с пространством настроек.
  example: []
  syntax:
    content: 'public interface ISettingsSpace : ISpace, IDisposable'
    content.vb: Public Interface ISettingsSpace Inherits ISpace, IDisposable
  inheritedMembers:
  - ParmaGIS.Modules.Data.Space.ISpace.Name
  - ParmaGIS.Modules.Data.Space.ISpace.Description
  - ParmaGIS.Modules.Data.Space.ISpace.Provider
  - System.IDisposable.Dispose
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace.Settings
  commentId: P:ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace.Settings
  id: Settings
  parent: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: ISettingsSpace.Settings
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace.Settings
  type: Property
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsSpace.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Settings
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsSpace.cs
    startLine: 10
  assemblies:
  - ParmaGIS.Modules.Data
  namespace: ParmaGIS.Modules.Data.Space.Settings
  summary: Возвращает репозиторий настроек.
  example: []
  syntax:
    content: ISettingsRepository Settings { get; }
    parameters: []
    return:
      type: ParmaGIS.Modules.Data.Space.Settings.ISettingsRepository
    content.vb: ReadOnly Property Settings As ISettingsRepository
  overload: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace.Settings*
references:
- uid: ParmaGIS.Modules.Data.Space.Settings
  commentId: N:ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Modules.Data.Space.Settings
  nameWithType: ParmaGIS.Modules.Data.Space.Settings
  fullName: ParmaGIS.Modules.Data.Space.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
- uid: ParmaGIS.Modules.Data.Space.ISpace.Name
  commentId: P:ParmaGIS.Modules.Data.Space.ISpace.Name
  parent: ParmaGIS.Modules.Data.Space.ISpace
  href: ParmaGIS.Modules.Data.Space.ISpace.html#ParmaGIS_Modules_Data_Space_ISpace_Name
  name: Name
  nameWithType: ISpace.Name
  fullName: ParmaGIS.Modules.Data.Space.ISpace.Name
- uid: ParmaGIS.Modules.Data.Space.ISpace.Description
  commentId: P:ParmaGIS.Modules.Data.Space.ISpace.Description
  parent: ParmaGIS.Modules.Data.Space.ISpace
  href: ParmaGIS.Modules.Data.Space.ISpace.html#ParmaGIS_Modules_Data_Space_ISpace_Description
  name: Description
  nameWithType: ISpace.Description
  fullName: ParmaGIS.Modules.Data.Space.ISpace.Description
- uid: ParmaGIS.Modules.Data.Space.ISpace.Provider
  commentId: P:ParmaGIS.Modules.Data.Space.ISpace.Provider
  parent: ParmaGIS.Modules.Data.Space.ISpace
  href: ParmaGIS.Modules.Data.Space.ISpace.html#ParmaGIS_Modules_Data_Space_ISpace_Provider
  name: Provider
  nameWithType: ISpace.Provider
  fullName: ParmaGIS.Modules.Data.Space.ISpace.Provider
- uid: System.IDisposable.Dispose
  commentId: M:System.IDisposable.Dispose
  parent: System.IDisposable
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  name: Dispose()
  nameWithType: IDisposable.Dispose()
  fullName: System.IDisposable.Dispose()
  spec.csharp:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
  spec.vb:
  - uid: System.IDisposable.Dispose
    name: Dispose
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.idisposable.dispose
  - name: (
  - name: )
- uid: ParmaGIS.Modules.Data.Space.ISpace
  commentId: T:ParmaGIS.Modules.Data.Space.ISpace
  parent: ParmaGIS.Modules.Data.Space
  href: ParmaGIS.Modules.Data.Space.ISpace.html
  name: ISpace
  nameWithType: ISpace
  fullName: ParmaGIS.Modules.Data.Space.ISpace
- uid: System.IDisposable
  commentId: T:System.IDisposable
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.idisposable
  name: IDisposable
  nameWithType: IDisposable
  fullName: System.IDisposable
- uid: ParmaGIS.Modules.Data.Space
  commentId: N:ParmaGIS.Modules.Data.Space
  href: ParmaGIS.html
  name: ParmaGIS.Modules.Data.Space
  nameWithType: ParmaGIS.Modules.Data.Space
  fullName: ParmaGIS.Modules.Data.Space
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace.Settings*
  commentId: Overload:ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace.Settings
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace.html#ParmaGIS_Modules_Data_Space_Settings_ISettingsSpace_Settings
  name: Settings
  nameWithType: ISettingsSpace.Settings
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace.Settings
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsRepository
  commentId: T:ParmaGIS.Modules.Data.Space.Settings.ISettingsRepository
  parent: ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsRepository.html
  name: ISettingsRepository
  nameWithType: ISettingsRepository
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsRepository
