### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
  id: BridgeSettingsWindows
  parent: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters
  children:
  - ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
  - ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
  - ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
  type: Namespace
references:
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
  commentId: N:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
  href: ParmaGIS.html
  name: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
  nameWithType: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool
    name: DataSpaceManagerTool
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters
    name: DataSpaceMasters
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
    name: BridgeSettingsWindows
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
    name: ViewModels
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool
    name: DataSpaceManagerTool
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters
    name: DataSpaceMasters
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
    name: BridgeSettingsWindows
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
    name: ViewModels
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.html
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
  commentId: N:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
  href: ParmaGIS.html
  name: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
  nameWithType: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool
    name: DataSpaceManagerTool
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters
    name: DataSpaceMasters
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
    name: BridgeSettingsWindows
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
    name: Viewmodels
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool
    name: DataSpaceManagerTool
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters
    name: DataSpaceMasters
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
    name: BridgeSettingsWindows
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
    name: Viewmodels
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels.html
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  commentId: N:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  href: ParmaGIS.html
  name: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  nameWithType: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool
    name: DataSpaceManagerTool
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters
    name: DataSpaceMasters
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
    name: BridgeSettingsWindows
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
    name: Views
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool
    name: DataSpaceManagerTool
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters
    name: DataSpaceMasters
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
    name: BridgeSettingsWindows
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
    name: Views
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.html
