### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  commentId: T:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  id: ISettingsSource
  parent: ParmaGIS.Shell.Services.SettingsManagement
  children:
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.GetSetting(System.Type,System.String,System.Type)
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.IsAutoSave
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Load
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Remove(System.Type,System.String)
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SaveTo(System.IO.Stream)
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetSetting(System.Type,System.String,System.Object)
  langs:
  - csharp
  - vb
  name: ISettingsSource
  nameWithType: ISettingsSource
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  type: Interface
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/dev
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: ISettingsSource
    path: ../../ParmaTest/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 5
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: public interface ISettingsSource
    content.vb: Public Interface ISettingsSource
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.IsAutoSave
  commentId: P:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.IsAutoSave
  id: IsAutoSave
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: IsAutoSave
  nameWithType: ISettingsSource.IsAutoSave
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.IsAutoSave
  type: Property
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/dev
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: IsAutoSave
    path: ../../ParmaTest/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 7
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: bool IsAutoSave { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property IsAutoSave As Boolean
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.IsAutoSave*
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.GetSetting(System.Type,System.String,System.Type)
  commentId: M:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.GetSetting(System.Type,System.String,System.Type)
  id: GetSetting(System.Type,System.String,System.Type)
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: GetSetting(Type, string, Type)
  nameWithType: ISettingsSource.GetSetting(Type, string, Type)
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.GetSetting(System.Type, string, System.Type)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/dev
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: GetSetting
    path: ../../ParmaTest/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 9
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: object? GetSetting(Type page, string key, Type settingType)
    parameters:
    - id: page
      type: System.Type
    - id: key
      type: System.String
    - id: settingType
      type: System.Type
    return:
      type: System.Object
    content.vb: Function GetSetting(page As Type, key As String, settingType As Type) As Object
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.GetSetting*
  nameWithType.vb: ISettingsSource.GetSetting(Type, String, Type)
  fullName.vb: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.GetSetting(System.Type, String, System.Type)
  name.vb: GetSetting(Type, String, Type)
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Load
  commentId: M:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Load
  id: Load
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: ISettingsSource.Load()
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Load()
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/dev
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Load
    path: ../../ParmaTest/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 10
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: void Load()
    content.vb: Sub Load()
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Load*
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Remove(System.Type,System.String)
  commentId: M:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Remove(System.Type,System.String)
  id: Remove(System.Type,System.String)
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: Remove(Type, string)
  nameWithType: ISettingsSource.Remove(Type, string)
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Remove(System.Type, string)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/dev
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Remove
    path: ../../ParmaTest/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 11
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: void Remove(Type page, string key)
    parameters:
    - id: page
      type: System.Type
    - id: key
      type: System.String
    content.vb: Sub Remove(page As Type, key As String)
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Remove*
  nameWithType.vb: ISettingsSource.Remove(Type, String)
  fullName.vb: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Remove(System.Type, String)
  name.vb: Remove(Type, String)
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save
  commentId: M:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save
  id: Save
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: Save()
  nameWithType: ISettingsSource.Save()
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save()
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/dev
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Save
    path: ../../ParmaTest/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 12
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: void Save()
    content.vb: Sub Save()
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save*
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SaveTo(System.IO.Stream)
  commentId: M:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SaveTo(System.IO.Stream)
  id: SaveTo(System.IO.Stream)
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: SaveTo(Stream)
  nameWithType: ISettingsSource.SaveTo(Stream)
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SaveTo(System.IO.Stream)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/dev
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: SaveTo
    path: ../../ParmaTest/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 13
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: void SaveTo(Stream stream)
    parameters:
    - id: stream
      type: System.IO.Stream
    content.vb: Sub SaveTo(stream As Stream)
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SaveTo*
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetSetting(System.Type,System.String,System.Object)
  commentId: M:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetSetting(System.Type,System.String,System.Object)
  id: SetSetting(System.Type,System.String,System.Object)
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: SetSetting(Type, string, object)
  nameWithType: ISettingsSource.SetSetting(Type, string, object)
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetSetting(System.Type, string, object)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/dev
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: SetSetting
    path: ../../ParmaTest/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 14
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: void SetSetting(Type page, string key, object value)
    parameters:
    - id: page
      type: System.Type
    - id: key
      type: System.String
    - id: value
      type: System.Object
    content.vb: Sub SetSetting(page As Type, key As String, value As Object)
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetSetting*
  nameWithType.vb: ISettingsSource.SetSetting(Type, String, Object)
  fullName.vb: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetSetting(System.Type, String, Object)
  name.vb: SetSetting(Type, String, Object)
references:
- uid: ParmaGIS.Shell.Services.SettingsManagement
  commentId: N:ParmaGIS.Shell.Services.SettingsManagement
  href: ParmaGIS.html
  name: ParmaGIS.Shell.Services.SettingsManagement
  nameWithType: ParmaGIS.Shell.Services.SettingsManagement
  fullName: ParmaGIS.Shell.Services.SettingsManagement
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Shell
    name: Shell
    href: ParmaGIS.Shell.html
  - name: .
  - uid: ParmaGIS.Shell.Services
    name: Services
    href: ParmaGIS.Shell.Services.html
  - name: .
  - uid: ParmaGIS.Shell.Services.SettingsManagement
    name: SettingsManagement
    href: ParmaGIS.Shell.Services.SettingsManagement.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Shell
    name: Shell
    href: ParmaGIS.Shell.html
  - name: .
  - uid: ParmaGIS.Shell.Services
    name: Services
    href: ParmaGIS.Shell.Services.html
  - name: .
  - uid: ParmaGIS.Shell.Services.SettingsManagement
    name: SettingsManagement
    href: ParmaGIS.Shell.Services.SettingsManagement.html
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.IsAutoSave*
  commentId: Overload:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.IsAutoSave
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html#ParmaGIS_Shell_Services_SettingsManagement_ISettingsSource_IsAutoSave
  name: IsAutoSave
  nameWithType: ISettingsSource.IsAutoSave
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.IsAutoSave
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.GetSetting*
  commentId: Overload:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.GetSetting
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html#ParmaGIS_Shell_Services_SettingsManagement_ISettingsSource_GetSetting_System_Type_System_String_System_Type_
  name: GetSetting
  nameWithType: ISettingsSource.GetSetting
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.GetSetting
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.type
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Load*
  commentId: Overload:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Load
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html#ParmaGIS_Shell_Services_SettingsManagement_ISettingsSource_Load
  name: Load
  nameWithType: ISettingsSource.Load
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Load
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Remove*
  commentId: Overload:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Remove
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html#ParmaGIS_Shell_Services_SettingsManagement_ISettingsSource_Remove_System_Type_System_String_
  name: Remove
  nameWithType: ISettingsSource.Remove
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Remove
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save*
  commentId: Overload:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html#ParmaGIS_Shell_Services_SettingsManagement_ISettingsSource_Save
  name: Save
  nameWithType: ISettingsSource.Save
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SaveTo*
  commentId: Overload:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SaveTo
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html#ParmaGIS_Shell_Services_SettingsManagement_ISettingsSource_SaveTo_System_IO_Stream_
  name: SaveTo
  nameWithType: ISettingsSource.SaveTo
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SaveTo
- uid: System.IO.Stream
  commentId: T:System.IO.Stream
  parent: System.IO
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.io.stream
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: System.IO
  commentId: N:System.IO
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.IO
  nameWithType: System.IO
  fullName: System.IO
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.IO
    name: IO
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.io
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.IO
    name: IO
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.io
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetSetting*
  commentId: Overload:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetSetting
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html#ParmaGIS_Shell_Services_SettingsManagement_ISettingsSource_SetSetting_System_Type_System_String_System_Object_
  name: SetSetting
  nameWithType: ISettingsSource.SetSetting
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetSetting
