### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Core.UI.Settings.Default
  commentId: N:ParmaGIS.Core.UI.Settings.Default
  id: Default
  parent: ParmaGIS.Core.UI.Settings
  children:
  - ParmaGIS.Core.UI.Settings.Default.DefaultSettingsParameter
  - ParmaGIS.Core.UI.Settings.Default.DefaultSettingsParameterGroup
  - ParmaGIS.Core.UI.Settings.Default.DefaultSettingsScope
  langs:
  - csharp
  - vb
  name: ParmaGIS.Core.UI.Settings.Default
  nameWithType: ParmaGIS.Core.UI.Settings.Default
  fullName: ParmaGIS.Core.UI.Settings.Default
  type: Namespace
  assemblies:
  - ParmaGIS.Core.UI
references:
- uid: ParmaGIS.Core.UI.Settings.Default.DefaultSettingsParameter
  commentId: T:ParmaGIS.Core.UI.Settings.Default.DefaultSettingsParameter
  parent: ParmaGIS.Core.UI.Settings.Default
  href: ParmaGIS.Core.UI.Settings.Default.DefaultSettingsParameter.html
  name: DefaultSettingsParameter
  nameWithType: DefaultSettingsParameter
  fullName: ParmaGIS.Core.UI.Settings.Default.DefaultSettingsParameter
- uid: ParmaGIS.Core.UI.Settings.Default.DefaultSettingsParameterGroup
  commentId: T:ParmaGIS.Core.UI.Settings.Default.DefaultSettingsParameterGroup
  href: ParmaGIS.Core.UI.Settings.Default.DefaultSettingsParameterGroup.html
  name: DefaultSettingsParameterGroup
  nameWithType: DefaultSettingsParameterGroup
  fullName: ParmaGIS.Core.UI.Settings.Default.DefaultSettingsParameterGroup
- uid: ParmaGIS.Core.UI.Settings.Default.DefaultSettingsScope
  commentId: T:ParmaGIS.Core.UI.Settings.Default.DefaultSettingsScope
  href: ParmaGIS.Core.UI.Settings.Default.DefaultSettingsScope.html
  name: DefaultSettingsScope
  nameWithType: DefaultSettingsScope
  fullName: ParmaGIS.Core.UI.Settings.Default.DefaultSettingsScope
- uid: ParmaGIS.Core.UI.Settings.Default
  commentId: N:ParmaGIS.Core.UI.Settings.Default
  href: ParmaGIS.html
  name: ParmaGIS.Core.UI.Settings.Default
  nameWithType: ParmaGIS.Core.UI.Settings.Default
  fullName: ParmaGIS.Core.UI.Settings.Default
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings.Default
    name: Default
    href: ParmaGIS.Core.UI.Settings.Default.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings.Default
    name: Default
    href: ParmaGIS.Core.UI.Settings.Default.html
