### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Shell.Services.SettingsManagement
  commentId: N:ParmaGIS.Shell.Services.SettingsManagement
  id: SettingsManagement
  parent: ParmaGIS.Shell.Services
  children:
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  - ParmaGIS.Shell.Services.SettingsManagement.LolKek
  - ParmaGIS.Shell.Services.SettingsManagement.SettingsManager
  - ParmaGIS.Shell.Services.SettingsManagement.SettingsPageProvider
  langs:
  - csharp
  - vb
  name: ParmaGIS.Shell.Services.SettingsManagement
  nameWithType: ParmaGIS.Shell.Services.SettingsManagement
  fullName: ParmaGIS.Shell.Services.SettingsManagement
  type: Namespace
  assemblies:
  - ParmaGIS.Shell
references:
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  commentId: T:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  parent: ParmaGIS.Shell.Services.SettingsManagement
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html
  name: ISettingsSource
  nameWithType: ISettingsSource
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
- uid: ParmaGIS.Shell.Services.SettingsManagement.LolKek
  commentId: T:ParmaGIS.Shell.Services.SettingsManagement.LolKek
  parent: ParmaGIS.Shell.Services.SettingsManagement
  href: ParmaGIS.Shell.Services.SettingsManagement.LolKek.html
  name: LolKek
  nameWithType: LolKek
  fullName: ParmaGIS.Shell.Services.SettingsManagement.LolKek
- uid: ParmaGIS.Shell.Services.SettingsManagement.SettingsManager
  commentId: T:ParmaGIS.Shell.Services.SettingsManagement.SettingsManager
  href: ParmaGIS.Shell.Services.SettingsManagement.SettingsManager.html
  name: SettingsManager
  nameWithType: SettingsManager
  fullName: ParmaGIS.Shell.Services.SettingsManagement.SettingsManager
- uid: ParmaGIS.Shell.Services.SettingsManagement.SettingsPageProvider
  commentId: T:ParmaGIS.Shell.Services.SettingsManagement.SettingsPageProvider
  href: ParmaGIS.Shell.Services.SettingsManagement.SettingsPageProvider.html
  name: SettingsPageProvider
  nameWithType: SettingsPageProvider
  fullName: ParmaGIS.Shell.Services.SettingsManagement.SettingsPageProvider
- uid: ParmaGIS.Shell.Services.SettingsManagement
  commentId: N:ParmaGIS.Shell.Services.SettingsManagement
  href: ParmaGIS.html
  name: ParmaGIS.Shell.Services.SettingsManagement
  nameWithType: ParmaGIS.Shell.Services.SettingsManagement
  fullName: ParmaGIS.Shell.Services.SettingsManagement
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Shell
    name: Shell
    href: ParmaGIS.Shell.html
  - name: .
  - uid: ParmaGIS.Shell.Services
    name: Services
    href: ParmaGIS.Shell.Services.html
  - name: .
  - uid: ParmaGIS.Shell.Services.SettingsManagement
    name: SettingsManagement
    href: ParmaGIS.Shell.Services.SettingsManagement.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Shell
    name: Shell
    href: ParmaGIS.Shell.html
  - name: .
  - uid: ParmaGIS.Shell.Services
    name: Services
    href: ParmaGIS.Shell.Services.html
  - name: .
  - uid: ParmaGIS.Shell.Services.SettingsManagement
    name: SettingsManagement
    href: ParmaGIS.Shell.Services.SettingsManagement.html
