### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Modules.Parma.Space.Settings
  commentId: N:ParmaGIS.Modules.Parma.Space.Settings
  id: Settings
  parent: ParmaGIS.Modules.Parma.Space
  children:
  - ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings
  - ParmaGIS.Modules.Parma.Space.Settings.CatalogItemSettings
  - ParmaGIS.Modules.Parma.Space.Settings.ForestGroupCuttingYearSettings
  - ParmaGIS.Modules.Parma.Space.Settings.OriginSettings
  - ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  - ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsRepository
  - ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord
  - ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesSettings
  - ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings
  langs:
  - csharp
  - vb
  name: ParmaGIS.Modules.Parma.Space.Settings
  nameWithType: ParmaGIS.Modules.Parma.Space.Settings
  fullName: ParmaGIS.Modules.Parma.Space.Settings
  type: Namespace
  assemblies:
  - ParmaGIS.Modules.Parma.Space
references:
- uid: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings
  href: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.html
  name: CalcTableSettings
  nameWithType: CalcTableSettings
  fullName: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings
- uid: ParmaGIS.Modules.Parma.Space.Settings.CatalogItemSettings
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.CatalogItemSettings
  href: ParmaGIS.Modules.Parma.Space.Settings.CatalogItemSettings.html
  name: CatalogItemSettings
  nameWithType: CatalogItemSettings
  fullName: ParmaGIS.Modules.Parma.Space.Settings.CatalogItemSettings
- uid: ParmaGIS.Modules.Parma.Space.Settings.ForestGroupCuttingYearSettings
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.ForestGroupCuttingYearSettings
  href: ParmaGIS.Modules.Parma.Space.Settings.ForestGroupCuttingYearSettings.html
  name: ForestGroupCuttingYearSettings
  nameWithType: ForestGroupCuttingYearSettings
  fullName: ParmaGIS.Modules.Parma.Space.Settings.ForestGroupCuttingYearSettings
- uid: ParmaGIS.Modules.Parma.Space.Settings.OriginSettings
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.OriginSettings
  href: ParmaGIS.Modules.Parma.Space.Settings.OriginSettings.html
  name: OriginSettings
  nameWithType: OriginSettings
  fullName: ParmaGIS.Modules.Parma.Space.Settings.OriginSettings
- uid: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  parent: ParmaGIS.Modules.Parma.Space.Settings
  href: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.html
  name: ParmaSettingsItem
  nameWithType: ParmaSettingsItem
  fullName: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
- uid: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsRepository
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsRepository
  parent: ParmaGIS.Modules.Parma.Space.Settings
  href: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsRepository.html
  name: ParmaSettingsRepository
  nameWithType: ParmaSettingsRepository
  fullName: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsRepository
- uid: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord
  parent: ParmaGIS.Modules.Parma.Space.Settings
  href: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.html
  name: SettingsRecord
  nameWithType: SettingsRecord
  fullName: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord
- uid: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesSettings
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesSettings
  href: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesSettings.html
  name: TreeSpeciesSettings
  nameWithType: TreeSpeciesSettings
  fullName: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesSettings
- uid: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings
  href: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.html
  name: TreeSpeciesTypeSettings
  nameWithType: TreeSpeciesTypeSettings
  fullName: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings
- uid: ParmaGIS.Modules.Parma.Space.Settings
  commentId: N:ParmaGIS.Modules.Parma.Space.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Modules.Parma.Space.Settings
  nameWithType: ParmaGIS.Modules.Parma.Space.Settings
  fullName: ParmaGIS.Modules.Parma.Space.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Parma
    name: Parma
    href: ParmaGIS.Modules.Parma.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space
    name: Space
    href: ParmaGIS.Modules.Parma.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Parma.Space.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Parma
    name: Parma
    href: ParmaGIS.Modules.Parma.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space
    name: Space
    href: ParmaGIS.Modules.Parma.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Parma.Space.Settings.html
