### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  commentId: T:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  id: ISettingsSource
  parent: ParmaGIS.Shell.Services.SettingsManagement
  children:
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Open(System.String)
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save(System.String)
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetValue(System.String,System.String,System.Object)
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue(System.String,System.String,System.Object@)
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue``1(System.String,System.String,``0@)
  langs:
  - csharp
  - vb
  name: ISettingsSource
  nameWithType: ISettingsSource
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  type: Interface
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: ISettingsSource
    path: ../ParmaGIS master/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 4
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: public interface ISettingsSource
    content.vb: Public Interface ISettingsSource
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue(System.String,System.String,System.Object@)
  commentId: M:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue(System.String,System.String,System.Object@)
  id: TryGetValue(System.String,System.String,System.Object@)
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: TryGetValue(string, string, out object)
  nameWithType: ISettingsSource.TryGetValue(string, string, out object)
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue(string, string, out object)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: TryGetValue
    path: ../ParmaGIS master/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 6
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: bool TryGetValue(string scope, string parameter, out object value)
    parameters:
    - id: scope
      type: System.String
    - id: parameter
      type: System.String
    - id: value
      type: System.Object
    return:
      type: System.Boolean
    content.vb: Function TryGetValue(scope As String, parameter As String, value As Object) As Boolean
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue*
  nameWithType.vb: ISettingsSource.TryGetValue(String, String, Object)
  fullName.vb: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue(String, String, Object)
  name.vb: TryGetValue(String, String, Object)
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue``1(System.String,System.String,``0@)
  commentId: M:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue``1(System.String,System.String,``0@)
  id: TryGetValue``1(System.String,System.String,``0@)
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: TryGetValue<T>(string, string, out T)
  nameWithType: ISettingsSource.TryGetValue<T>(string, string, out T)
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue<T>(string, string, out T)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: TryGetValue
    path: ../ParmaGIS master/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 7
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: bool TryGetValue<T>(string scope, string parameter, out T value)
    parameters:
    - id: scope
      type: System.String
    - id: parameter
      type: System.String
    - id: value
      type: '{T}'
    typeParameters:
    - id: T
    return:
      type: System.Boolean
    content.vb: Function TryGetValue(Of T)(scope As String, parameter As String, value As T) As Boolean
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue*
  nameWithType.vb: ISettingsSource.TryGetValue(Of T)(String, String, T)
  fullName.vb: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue(Of T)(String, String, T)
  name.vb: TryGetValue(Of T)(String, String, T)
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetValue(System.String,System.String,System.Object)
  commentId: M:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetValue(System.String,System.String,System.Object)
  id: SetValue(System.String,System.String,System.Object)
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: SetValue(string, string, object)
  nameWithType: ISettingsSource.SetValue(string, string, object)
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetValue(string, string, object)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: SetValue
    path: ../ParmaGIS master/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 8
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: void SetValue(string scope, string parameter, object value)
    parameters:
    - id: scope
      type: System.String
    - id: parameter
      type: System.String
    - id: value
      type: System.Object
    content.vb: Sub SetValue(scope As String, parameter As String, value As Object)
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetValue*
  nameWithType.vb: ISettingsSource.SetValue(String, String, Object)
  fullName.vb: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetValue(String, String, Object)
  name.vb: SetValue(String, String, Object)
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save(System.String)
  commentId: M:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save(System.String)
  id: Save(System.String)
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: Save(string)
  nameWithType: ISettingsSource.Save(string)
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save(string)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Save
    path: ../ParmaGIS master/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 9
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: void Save(string path)
    parameters:
    - id: path
      type: System.String
    content.vb: Sub Save(path As String)
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save*
  nameWithType.vb: ISettingsSource.Save(String)
  fullName.vb: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save(String)
  name.vb: Save(String)
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Open(System.String)
  commentId: M:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Open(System.String)
  id: Open(System.String)
  parent: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: Open(string)
  nameWithType: ISettingsSource.Open(string)
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Open(string)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Open
    path: ../ParmaGIS master/common/src/ParmaGIS.Shell/Services/SettingsManagement/ISettingsSource.cs
    startLine: 10
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: void Open(string path)
    parameters:
    - id: path
      type: System.String
    content.vb: Sub Open(path As String)
  overload: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Open*
  nameWithType.vb: ISettingsSource.Open(String)
  fullName.vb: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Open(String)
  name.vb: Open(String)
references:
- uid: ParmaGIS.Shell.Services.SettingsManagement
  commentId: N:ParmaGIS.Shell.Services.SettingsManagement
  href: ParmaGIS.html
  name: ParmaGIS.Shell.Services.SettingsManagement
  nameWithType: ParmaGIS.Shell.Services.SettingsManagement
  fullName: ParmaGIS.Shell.Services.SettingsManagement
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Shell
    name: Shell
    href: ParmaGIS.Shell.html
  - name: .
  - uid: ParmaGIS.Shell.Services
    name: Services
    href: ParmaGIS.Shell.Services.html
  - name: .
  - uid: ParmaGIS.Shell.Services.SettingsManagement
    name: SettingsManagement
    href: ParmaGIS.Shell.Services.SettingsManagement.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Shell
    name: Shell
    href: ParmaGIS.Shell.html
  - name: .
  - uid: ParmaGIS.Shell.Services
    name: Services
    href: ParmaGIS.Shell.Services.html
  - name: .
  - uid: ParmaGIS.Shell.Services.SettingsManagement
    name: SettingsManagement
    href: ParmaGIS.Shell.Services.SettingsManagement.html
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue*
  commentId: Overload:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html#ParmaGIS_Shell_Services_SettingsManagement_ISettingsSource_TryGetValue_System_String_System_String_System_Object__
  name: TryGetValue
  nameWithType: ISettingsSource.TryGetValue
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.TryGetValue
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetValue*
  commentId: Overload:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetValue
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html#ParmaGIS_Shell_Services_SettingsManagement_ISettingsSource_SetValue_System_String_System_String_System_Object_
  name: SetValue
  nameWithType: ISettingsSource.SetValue
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.SetValue
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save*
  commentId: Overload:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html#ParmaGIS_Shell_Services_SettingsManagement_ISettingsSource_Save_System_String_
  name: Save
  nameWithType: ISettingsSource.Save
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Save
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Open*
  commentId: Overload:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Open
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html#ParmaGIS_Shell_Services_SettingsManagement_ISettingsSource_Open_System_String_
  name: Open
  nameWithType: ISettingsSource.Open
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.Open
