### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension
  commentId: T:ParmaGIS.Core.UI.Settings.ServiceCollectionExtension
  id: ServiceCollectionExtension
  parent: ParmaGIS.Core.UI.Settings
  children:
  - ParmaGIS.Core.UI.Settings.ServiceCollectionExtension.RegisterSettingsScope(ParmaGIS.Core.Serviceability.IServiceCollection,ParmaGIS.Core.UI.Settings.ISettingsScope)
  langs:
  - csharp
  - vb
  name: ServiceCollectionExtension
  nameWithType: ServiceCollectionExtension
  fullName: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension
  type: Class
  source:
    remote:
      path: common/src/ParmaGIS.Core.UI/Settings/ServiceCollectionExtension.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: ServiceCollectionExtension
    path: ../ParmaGIS master/common/src/ParmaGIS.Core.UI/Settings/ServiceCollectionExtension.cs
    startLine: 10
  assemblies:
  - ParmaGIS.Core.UI
  namespace: ParmaGIS.Core.UI.Settings
  summary: Представляет методы расширения для <xref href="ParmaGIS.Core.Serviceability.IServiceCollection" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static class ServiceCollectionExtension
    content.vb: Public Module ServiceCollectionExtension
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension.RegisterSettingsScope(ParmaGIS.Core.Serviceability.IServiceCollection,ParmaGIS.Core.UI.Settings.ISettingsScope)
  commentId: M:ParmaGIS.Core.UI.Settings.ServiceCollectionExtension.RegisterSettingsScope(ParmaGIS.Core.Serviceability.IServiceCollection,ParmaGIS.Core.UI.Settings.ISettingsScope)
  id: RegisterSettingsScope(ParmaGIS.Core.Serviceability.IServiceCollection,ParmaGIS.Core.UI.Settings.ISettingsScope)
  isExtensionMethod: true
  parent: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension
  langs:
  - csharp
  - vb
  name: RegisterSettingsScope(IServiceCollection, ISettingsScope)
  nameWithType: ServiceCollectionExtension.RegisterSettingsScope(IServiceCollection, ISettingsScope)
  fullName: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension.RegisterSettingsScope(ParmaGIS.Core.Serviceability.IServiceCollection, ParmaGIS.Core.UI.Settings.ISettingsScope)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Core.UI/Settings/ServiceCollectionExtension.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: RegisterSettingsScope
    path: ../ParmaGIS master/common/src/ParmaGIS.Core.UI/Settings/ServiceCollectionExtension.cs
    startLine: 18
  assemblies:
  - ParmaGIS.Core.UI
  namespace: ParmaGIS.Core.UI.Settings
  summary: Регистрирует область настроек.
  example: []
  syntax:
    content: public static void RegisterSettingsScope(this IServiceCollection services, ISettingsScope scope)
    parameters:
    - id: services
      type: ParmaGIS.Core.Serviceability.IServiceCollection
      description: Коллекция сервисов.
    - id: scope
      type: ParmaGIS.Core.UI.Settings.ISettingsScope
      description: Область настроек.
    content.vb: Public Shared Sub RegisterSettingsScope(services As IServiceCollection, scope As ISettingsScope)
  overload: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension.RegisterSettingsScope*
  exceptions:
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: ''
references:
- uid: ParmaGIS.Core.Serviceability.IServiceCollection
  commentId: T:ParmaGIS.Core.Serviceability.IServiceCollection
  parent: ParmaGIS.Core.Serviceability
  href: ParmaGIS.Core.Serviceability.IServiceCollection.html
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: ParmaGIS.Core.Serviceability.IServiceCollection
- uid: ParmaGIS.Core.UI.Settings
  commentId: N:ParmaGIS.Core.UI.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Core.UI.Settings
  nameWithType: ParmaGIS.Core.UI.Settings
  fullName: ParmaGIS.Core.UI.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: ParmaGIS.Core.Serviceability
  commentId: N:ParmaGIS.Core.Serviceability
  href: ParmaGIS.html
  name: ParmaGIS.Core.Serviceability
  nameWithType: ParmaGIS.Core.Serviceability
  fullName: ParmaGIS.Core.Serviceability
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.Serviceability
    name: Serviceability
    href: ParmaGIS.Core.Serviceability.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.Serviceability
    name: Serviceability
    href: ParmaGIS.Core.Serviceability.html
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.InvalidOperationException
  commentId: T:System.InvalidOperationException
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.invalidoperationexception
  name: InvalidOperationException
  nameWithType: InvalidOperationException
  fullName: System.InvalidOperationException
- uid: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension.RegisterSettingsScope*
  commentId: Overload:ParmaGIS.Core.UI.Settings.ServiceCollectionExtension.RegisterSettingsScope
  href: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension.html#ParmaGIS_Core_UI_Settings_ServiceCollectionExtension_RegisterSettingsScope_ParmaGIS_Core_Serviceability_IServiceCollection_ParmaGIS_Core_UI_Settings_ISettingsScope_
  name: RegisterSettingsScope
  nameWithType: ServiceCollectionExtension.RegisterSettingsScope
  fullName: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension.RegisterSettingsScope
- uid: ParmaGIS.Core.UI.Settings.ISettingsScope
  commentId: T:ParmaGIS.Core.UI.Settings.ISettingsScope
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.ISettingsScope.html
  name: ISettingsScope
  nameWithType: ISettingsScope
  fullName: ParmaGIS.Core.UI.Settings.ISettingsScope
