### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Core.UI.Settings
  commentId: N:ParmaGIS.Core.UI.Settings
  id: Settings
  parent: ParmaGIS.Core.UI
  children:
  - ParmaGIS.Core.UI.Settings.Default
  - ParmaGIS.Core.UI.Settings.ISettingsManager
  - ParmaGIS.Core.UI.Settings.ISettingsParameter
  - ParmaGIS.Core.UI.Settings.ISettingsParameterGroup
  - ParmaGIS.Core.UI.Settings.ISettingsProvider
  - ParmaGIS.Core.UI.Settings.ISettingsScope
  - ParmaGIS.Core.UI.Settings.ISettingsScopeCatalog
  - ParmaGIS.Core.UI.Settings.ServiceCollectionExtension
  - ParmaGIS.Core.UI.Settings.SettingsScopeLocator
  langs:
  - csharp
  - vb
  name: ParmaGIS.Core.UI.Settings
  nameWithType: ParmaGIS.Core.UI.Settings
  fullName: ParmaGIS.Core.UI.Settings
  type: Namespace
  assemblies:
  - ParmaGIS.Core.UI
references:
- uid: ParmaGIS.Core.UI.Settings.Default
  commentId: N:ParmaGIS.Core.UI.Settings.Default
  href: ParmaGIS.html
  name: ParmaGIS.Core.UI.Settings.Default
  nameWithType: ParmaGIS.Core.UI.Settings.Default
  fullName: ParmaGIS.Core.UI.Settings.Default
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings.Default
    name: Default
    href: ParmaGIS.Core.UI.Settings.Default.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings.Default
    name: Default
    href: ParmaGIS.Core.UI.Settings.Default.html
- uid: ParmaGIS.Core.UI.Settings.ISettingsManager
  commentId: T:ParmaGIS.Core.UI.Settings.ISettingsManager
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.ISettingsManager.html
  name: ISettingsManager
  nameWithType: ISettingsManager
  fullName: ParmaGIS.Core.UI.Settings.ISettingsManager
- uid: ParmaGIS.Core.UI.Settings.ISettingsParameter
  commentId: T:ParmaGIS.Core.UI.Settings.ISettingsParameter
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.ISettingsParameter.html
  name: ISettingsParameter
  nameWithType: ISettingsParameter
  fullName: ParmaGIS.Core.UI.Settings.ISettingsParameter
- uid: ParmaGIS.Core.UI.Settings.ISettingsParameterGroup
  commentId: T:ParmaGIS.Core.UI.Settings.ISettingsParameterGroup
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.ISettingsParameterGroup.html
  name: ISettingsParameterGroup
  nameWithType: ISettingsParameterGroup
  fullName: ParmaGIS.Core.UI.Settings.ISettingsParameterGroup
- uid: ParmaGIS.Core.UI.Settings.ISettingsProvider
  commentId: T:ParmaGIS.Core.UI.Settings.ISettingsProvider
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.ISettingsProvider.html
  name: ISettingsProvider
  nameWithType: ISettingsProvider
  fullName: ParmaGIS.Core.UI.Settings.ISettingsProvider
- uid: ParmaGIS.Core.UI.Settings.ISettingsScope
  commentId: T:ParmaGIS.Core.UI.Settings.ISettingsScope
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.ISettingsScope.html
  name: ISettingsScope
  nameWithType: ISettingsScope
  fullName: ParmaGIS.Core.UI.Settings.ISettingsScope
- uid: ParmaGIS.Core.UI.Settings.ISettingsScopeCatalog
  commentId: T:ParmaGIS.Core.UI.Settings.ISettingsScopeCatalog
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.ISettingsScopeCatalog.html
  name: ISettingsScopeCatalog
  nameWithType: ISettingsScopeCatalog
  fullName: ParmaGIS.Core.UI.Settings.ISettingsScopeCatalog
- uid: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension
  commentId: T:ParmaGIS.Core.UI.Settings.ServiceCollectionExtension
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension.html
  name: ServiceCollectionExtension
  nameWithType: ServiceCollectionExtension
  fullName: ParmaGIS.Core.UI.Settings.ServiceCollectionExtension
- uid: ParmaGIS.Core.UI.Settings.SettingsScopeLocator
  commentId: T:ParmaGIS.Core.UI.Settings.SettingsScopeLocator
  href: ParmaGIS.Core.UI.Settings.SettingsScopeLocator.html
  name: SettingsScopeLocator
  nameWithType: SettingsScopeLocator
  fullName: ParmaGIS.Core.UI.Settings.SettingsScopeLocator
- uid: ParmaGIS.Core.UI.Settings
  commentId: N:ParmaGIS.Core.UI.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Core.UI.Settings
  nameWithType: ParmaGIS.Core.UI.Settings
  fullName: ParmaGIS.Core.UI.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
