### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  commentId: N:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  id: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  children:
  - ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.BridgeSettings
  - ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.BridgeSettingsWindow
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  nameWithType: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.DataSpaceManagerTool
references:
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.BridgeSettings
  commentId: T:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.BridgeSettings
  parent: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.BridgeSettings.html
  name: BridgeSettings
  nameWithType: BridgeSettings
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.BridgeSettings
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.BridgeSettingsWindow
  commentId: T:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.BridgeSettingsWindow
  href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.BridgeSettingsWindow.html
  name: BridgeSettingsWindow
  nameWithType: BridgeSettingsWindow
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.BridgeSettingsWindow
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  commentId: N:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  href: ParmaGIS.html
  name: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  nameWithType: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool
    name: DataSpaceManagerTool
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters
    name: DataSpaceMasters
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
    name: BridgeSettingsWindows
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
    name: Views
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool
    name: DataSpaceManagerTool
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters
    name: DataSpaceMasters
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
    name: BridgeSettingsWindows
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views
    name: Views
    href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Views.html
