### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.DepartmentSettings
  commentId: N:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.DepartmentSettings
  id: DepartmentSettings
  parent: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views
  children:
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.DepartmentSettings.DepartmentDefaultSettingsView
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.DepartmentSettings
  nameWithType: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.DepartmentSettings
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.DepartmentSettings
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.Parma.UI
references:
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.DepartmentSettings.DepartmentDefaultSettingsView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.DepartmentSettings.DepartmentDefaultSettingsView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.DepartmentSettings.DepartmentDefaultSettingsView.html
  name: DepartmentDefaultSettingsView
  nameWithType: DepartmentDefaultSettingsView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.DepartmentSettings.DepartmentDefaultSettingsView
