### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings
  id: TreeSpeciesTypeSettings
  parent: ParmaGIS.Modules.Parma.Space.Settings
  children:
  - ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.AgeClassRange
  - ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.Order
  langs:
  - csharp
  - vb
  name: TreeSpeciesTypeSettings
  nameWithType: TreeSpeciesTypeSettings
  fullName: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings
  type: Class
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: TreeSpeciesTypeSettings
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
    startLine: 72
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: 'public class TreeSpeciesTypeSettings : ParmaSettingsItem, ISettingsItem'
    content.vb: Public Class TreeSpeciesTypeSettings Inherits ParmaSettingsItem Implements ISettingsItem
  inheritance:
  - System.Object
  - ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  implements:
  - ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
  inheritedMembers:
  - ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Id
  - ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.RecordId
  - ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Record
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.Order
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.Order
  id: Order
  parent: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings
  langs:
  - csharp
  - vb
  name: Order
  nameWithType: TreeSpeciesTypeSettings.Order
  fullName: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.Order
  type: Property
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Order
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
    startLine: 74
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: public int Order { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Order As Integer
  overload: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.Order*
- uid: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.AgeClassRange
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.AgeClassRange
  id: AgeClassRange
  parent: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings
  langs:
  - csharp
  - vb
  name: AgeClassRange
  nameWithType: TreeSpeciesTypeSettings.AgeClassRange
  fullName: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.AgeClassRange
  type: Property
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: AgeClassRange
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
    startLine: 75
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: public int AgeClassRange { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property AgeClassRange As Integer
  overload: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.AgeClassRange*
references:
- uid: ParmaGIS.Modules.Parma.Space.Settings
  commentId: N:ParmaGIS.Modules.Parma.Space.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Modules.Parma.Space.Settings
  nameWithType: ParmaGIS.Modules.Parma.Space.Settings
  fullName: ParmaGIS.Modules.Parma.Space.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Parma
    name: Parma
    href: ParmaGIS.Modules.Parma.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space
    name: Space
    href: ParmaGIS.Modules.Parma.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Parma.Space.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Parma
    name: Parma
    href: ParmaGIS.Modules.Parma.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space
    name: Space
    href: ParmaGIS.Modules.Parma.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Parma.Space.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  parent: ParmaGIS.Modules.Parma.Space.Settings
  href: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.html
  name: ParmaSettingsItem
  nameWithType: ParmaSettingsItem
  fullName: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
  commentId: T:ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
  parent: ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsItem.html
  name: ISettingsItem
  nameWithType: ISettingsItem
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
- uid: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Id
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Id
  parent: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  href: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.html#ParmaGIS_Modules_Parma_Space_Settings_ParmaSettingsItem_Id
  name: Id
  nameWithType: ParmaSettingsItem.Id
  fullName: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Id
- uid: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.RecordId
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.RecordId
  parent: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  href: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.html#ParmaGIS_Modules_Parma_Space_Settings_ParmaSettingsItem_RecordId
  name: RecordId
  nameWithType: ParmaSettingsItem.RecordId
  fullName: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.RecordId
- uid: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Record
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Record
  parent: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  href: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.html#ParmaGIS_Modules_Parma_Space_Settings_ParmaSettingsItem_Record
  name: Record
  nameWithType: ParmaSettingsItem.Record
  fullName: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Record
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ParmaGIS.Modules.Data.Space.Settings
  commentId: N:ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Modules.Data.Space.Settings
  nameWithType: ParmaGIS.Modules.Data.Space.Settings
  fullName: ParmaGIS.Modules.Data.Space.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
- uid: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.Order*
  commentId: Overload:ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.Order
  href: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.html#ParmaGIS_Modules_Parma_Space_Settings_TreeSpeciesTypeSettings_Order
  name: Order
  nameWithType: TreeSpeciesTypeSettings.Order
  fullName: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.Order
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.AgeClassRange*
  commentId: Overload:ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.AgeClassRange
  href: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.html#ParmaGIS_Modules_Parma_Space_Settings_TreeSpeciesTypeSettings_AgeClassRange
  name: AgeClassRange
  nameWithType: TreeSpeciesTypeSettings.AgeClassRange
  fullName: ParmaGIS.Modules.Parma.Space.Settings.TreeSpeciesTypeSettings.AgeClassRange
