### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Core.UI.Settings
  commentId: N:ParmaGIS.Core.UI.Settings
  id: ParmaGIS.Core.UI.Settings
  children:
  - ParmaGIS.Core.UI.Settings.AppSettingsPage
  - ParmaGIS.Core.UI.Settings.DefaultAttribute
  - ParmaGIS.Core.UI.Settings.DescriptionAttribute
  - ParmaGIS.Core.UI.Settings.EnumDescriptionsAttribute
  - ParmaGIS.Core.UI.Settings.EnumTitlesAttribute
  - ParmaGIS.Core.UI.Settings.ISettingsManager
  - ParmaGIS.Core.UI.Settings.SettingErrorEventArgs
  - ParmaGIS.Core.UI.Settings.SettingInfo
  - ParmaGIS.Core.UI.Settings.SettingsAttribute
  - ParmaGIS.Core.UI.Settings.SettingsExtensions
  - ParmaGIS.Core.UI.Settings.SettingsPage
  - ParmaGIS.Core.UI.Settings.SettingsPageInfo
  - ParmaGIS.Core.UI.Settings.SettingsProvider`1
  - ParmaGIS.Core.UI.Settings.SettingsValidationAttribute
  - ParmaGIS.Core.UI.Settings.TitleAttribute
  langs:
  - csharp
  - vb
  name: ParmaGIS.Core.UI.Settings
  nameWithType: ParmaGIS.Core.UI.Settings
  fullName: ParmaGIS.Core.UI.Settings
  type: Namespace
  assemblies:
  - ParmaGIS.Core.UI
references:
- uid: ParmaGIS.Core.UI.Settings.AppSettingsPage
  commentId: T:ParmaGIS.Core.UI.Settings.AppSettingsPage
  href: ParmaGIS.Core.UI.Settings.AppSettingsPage.html
  name: AppSettingsPage
  nameWithType: AppSettingsPage
  fullName: ParmaGIS.Core.UI.Settings.AppSettingsPage
- uid: ParmaGIS.Core.UI.Settings.DefaultAttribute
  commentId: T:ParmaGIS.Core.UI.Settings.DefaultAttribute
  href: ParmaGIS.Core.UI.Settings.DefaultAttribute.html
  name: DefaultAttribute
  nameWithType: DefaultAttribute
  fullName: ParmaGIS.Core.UI.Settings.DefaultAttribute
- uid: ParmaGIS.Core.UI.Settings.DescriptionAttribute
  commentId: T:ParmaGIS.Core.UI.Settings.DescriptionAttribute
  href: ParmaGIS.Core.UI.Settings.DescriptionAttribute.html
  name: DescriptionAttribute
  nameWithType: DescriptionAttribute
  fullName: ParmaGIS.Core.UI.Settings.DescriptionAttribute
- uid: ParmaGIS.Core.UI.Settings.EnumDescriptionsAttribute
  commentId: T:ParmaGIS.Core.UI.Settings.EnumDescriptionsAttribute
  href: ParmaGIS.Core.UI.Settings.EnumDescriptionsAttribute.html
  name: EnumDescriptionsAttribute
  nameWithType: EnumDescriptionsAttribute
  fullName: ParmaGIS.Core.UI.Settings.EnumDescriptionsAttribute
- uid: ParmaGIS.Core.UI.Settings.EnumTitlesAttribute
  commentId: T:ParmaGIS.Core.UI.Settings.EnumTitlesAttribute
  href: ParmaGIS.Core.UI.Settings.EnumTitlesAttribute.html
  name: EnumTitlesAttribute
  nameWithType: EnumTitlesAttribute
  fullName: ParmaGIS.Core.UI.Settings.EnumTitlesAttribute
- uid: ParmaGIS.Core.UI.Settings.ISettingsManager
  commentId: T:ParmaGIS.Core.UI.Settings.ISettingsManager
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.ISettingsManager.html
  name: ISettingsManager
  nameWithType: ISettingsManager
  fullName: ParmaGIS.Core.UI.Settings.ISettingsManager
- uid: ParmaGIS.Core.UI.Settings.SettingErrorEventArgs
  commentId: T:ParmaGIS.Core.UI.Settings.SettingErrorEventArgs
  href: ParmaGIS.Core.UI.Settings.SettingErrorEventArgs.html
  name: SettingErrorEventArgs
  nameWithType: SettingErrorEventArgs
  fullName: ParmaGIS.Core.UI.Settings.SettingErrorEventArgs
- uid: ParmaGIS.Core.UI.Settings.SettingInfo
  commentId: T:ParmaGIS.Core.UI.Settings.SettingInfo
  href: ParmaGIS.Core.UI.Settings.SettingInfo.html
  name: SettingInfo
  nameWithType: SettingInfo
  fullName: ParmaGIS.Core.UI.Settings.SettingInfo
- uid: ParmaGIS.Core.UI.Settings.SettingsAttribute
  commentId: T:ParmaGIS.Core.UI.Settings.SettingsAttribute
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.SettingsAttribute.html
  name: SettingsAttribute
  nameWithType: SettingsAttribute
  fullName: ParmaGIS.Core.UI.Settings.SettingsAttribute
- uid: ParmaGIS.Core.UI.Settings.SettingsExtensions
  commentId: T:ParmaGIS.Core.UI.Settings.SettingsExtensions
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.SettingsExtensions.html
  name: SettingsExtensions
  nameWithType: SettingsExtensions
  fullName: ParmaGIS.Core.UI.Settings.SettingsExtensions
- uid: ParmaGIS.Core.UI.Settings.SettingsPage
  commentId: T:ParmaGIS.Core.UI.Settings.SettingsPage
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.SettingsPage.html
  name: SettingsPage
  nameWithType: SettingsPage
  fullName: ParmaGIS.Core.UI.Settings.SettingsPage
- uid: ParmaGIS.Core.UI.Settings.SettingsPageInfo
  commentId: T:ParmaGIS.Core.UI.Settings.SettingsPageInfo
  parent: ParmaGIS.Core.UI.Settings
  href: ParmaGIS.Core.UI.Settings.SettingsPageInfo.html
  name: SettingsPageInfo
  nameWithType: SettingsPageInfo
  fullName: ParmaGIS.Core.UI.Settings.SettingsPageInfo
- uid: ParmaGIS.Core.UI.Settings.SettingsProvider`1
  commentId: T:ParmaGIS.Core.UI.Settings.SettingsProvider`1
  href: ParmaGIS.Core.UI.Settings.SettingsProvider-1.html
  name: SettingsProvider<T>
  nameWithType: SettingsProvider<T>
  fullName: ParmaGIS.Core.UI.Settings.SettingsProvider<T>
  nameWithType.vb: SettingsProvider(Of T)
  fullName.vb: ParmaGIS.Core.UI.Settings.SettingsProvider(Of T)
  name.vb: SettingsProvider(Of T)
  spec.csharp:
  - uid: ParmaGIS.Core.UI.Settings.SettingsProvider`1
    name: SettingsProvider
    href: ParmaGIS.Core.UI.Settings.SettingsProvider-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: ParmaGIS.Core.UI.Settings.SettingsProvider`1
    name: SettingsProvider
    href: ParmaGIS.Core.UI.Settings.SettingsProvider-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: ParmaGIS.Core.UI.Settings.SettingsValidationAttribute
  commentId: T:ParmaGIS.Core.UI.Settings.SettingsValidationAttribute
  href: ParmaGIS.Core.UI.Settings.SettingsValidationAttribute.html
  name: SettingsValidationAttribute
  nameWithType: SettingsValidationAttribute
  fullName: ParmaGIS.Core.UI.Settings.SettingsValidationAttribute
- uid: ParmaGIS.Core.UI.Settings.TitleAttribute
  commentId: T:ParmaGIS.Core.UI.Settings.TitleAttribute
  href: ParmaGIS.Core.UI.Settings.TitleAttribute.html
  name: TitleAttribute
  nameWithType: TitleAttribute
  fullName: ParmaGIS.Core.UI.Settings.TitleAttribute
- uid: ParmaGIS.Core.UI.Settings
  commentId: N:ParmaGIS.Core.UI.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Core.UI.Settings
  nameWithType: ParmaGIS.Core.UI.Settings
  fullName: ParmaGIS.Core.UI.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
