### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings
  id: CalcTableSettings
  parent: ParmaGIS.Modules.Parma.Space.Settings
  children:
  - ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.#ctor
  - ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.#ctor(System.Guid,System.Guid)
  - ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.IsReferenced
  langs:
  - csharp
  - vb
  name: CalcTableSettings
  nameWithType: CalcTableSettings
  fullName: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings
  type: Class
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: CalcTableSettings
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
    startLine: 32
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: 'public class CalcTableSettings : ParmaSettingsItem, ISettingsItem'
    content.vb: Public Class CalcTableSettings Inherits ParmaSettingsItem Implements ISettingsItem
  inheritance:
  - System.Object
  - ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  implements:
  - ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
  inheritedMembers:
  - ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Id
  - ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.RecordId
  - ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Record
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.#ctor
  commentId: M:ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.#ctor
  id: '#ctor'
  parent: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings
  langs:
  - csharp
  - vb
  name: CalcTableSettings()
  nameWithType: CalcTableSettings.CalcTableSettings()
  fullName: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.CalcTableSettings()
  type: Constructor
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: .ctor
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
    startLine: 34
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: public CalcTableSettings()
    content.vb: Public Sub New()
  overload: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.#ctor*
  nameWithType.vb: CalcTableSettings.New()
  fullName.vb: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.New()
  name.vb: New()
- uid: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.#ctor(System.Guid,System.Guid)
  commentId: M:ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.#ctor(System.Guid,System.Guid)
  id: '#ctor(System.Guid,System.Guid)'
  parent: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings
  langs:
  - csharp
  - vb
  name: CalcTableSettings(Guid, Guid)
  nameWithType: CalcTableSettings.CalcTableSettings(Guid, Guid)
  fullName: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.CalcTableSettings(System.Guid, System.Guid)
  type: Constructor
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: .ctor
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
    startLine: 38
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: public CalcTableSettings(Guid scopeId, Guid subjectId)
    parameters:
    - id: scopeId
      type: System.Guid
    - id: subjectId
      type: System.Guid
    content.vb: Public Sub New(scopeId As Guid, subjectId As Guid)
  overload: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.#ctor*
  nameWithType.vb: CalcTableSettings.New(Guid, Guid)
  fullName.vb: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.New(System.Guid, System.Guid)
  name.vb: New(Guid, Guid)
- uid: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.IsReferenced
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.IsReferenced
  id: IsReferenced
  parent: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings
  langs:
  - csharp
  - vb
  name: IsReferenced
  nameWithType: CalcTableSettings.IsReferenced
  fullName: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.IsReferenced
  type: Property
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: IsReferenced
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/Settings.cs
    startLine: 43
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: public bool IsReferenced { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsReferenced As Boolean
  overload: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.IsReferenced*
references:
- uid: ParmaGIS.Modules.Parma.Space.Settings
  commentId: N:ParmaGIS.Modules.Parma.Space.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Modules.Parma.Space.Settings
  nameWithType: ParmaGIS.Modules.Parma.Space.Settings
  fullName: ParmaGIS.Modules.Parma.Space.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Parma
    name: Parma
    href: ParmaGIS.Modules.Parma.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space
    name: Space
    href: ParmaGIS.Modules.Parma.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Parma.Space.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Parma
    name: Parma
    href: ParmaGIS.Modules.Parma.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space
    name: Space
    href: ParmaGIS.Modules.Parma.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Parma.Space.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  parent: ParmaGIS.Modules.Parma.Space.Settings
  href: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.html
  name: ParmaSettingsItem
  nameWithType: ParmaSettingsItem
  fullName: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
  commentId: T:ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
  parent: ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsItem.html
  name: ISettingsItem
  nameWithType: ISettingsItem
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
- uid: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Id
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Id
  parent: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  href: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.html#ParmaGIS_Modules_Parma_Space_Settings_ParmaSettingsItem_Id
  name: Id
  nameWithType: ParmaSettingsItem.Id
  fullName: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Id
- uid: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.RecordId
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.RecordId
  parent: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  href: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.html#ParmaGIS_Modules_Parma_Space_Settings_ParmaSettingsItem_RecordId
  name: RecordId
  nameWithType: ParmaSettingsItem.RecordId
  fullName: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.RecordId
- uid: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Record
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Record
  parent: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem
  href: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.html#ParmaGIS_Modules_Parma_Space_Settings_ParmaSettingsItem_Record
  name: Record
  nameWithType: ParmaSettingsItem.Record
  fullName: ParmaGIS.Modules.Parma.Space.Settings.ParmaSettingsItem.Record
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ParmaGIS.Modules.Data.Space.Settings
  commentId: N:ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Modules.Data.Space.Settings
  nameWithType: ParmaGIS.Modules.Data.Space.Settings
  fullName: ParmaGIS.Modules.Data.Space.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
- uid: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.#ctor*
  commentId: Overload:ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.#ctor
  href: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.html#ParmaGIS_Modules_Parma_Space_Settings_CalcTableSettings__ctor
  name: CalcTableSettings
  nameWithType: CalcTableSettings.CalcTableSettings
  fullName: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.CalcTableSettings
  nameWithType.vb: CalcTableSettings.New
  fullName.vb: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.New
  name.vb: New
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.IsReferenced*
  commentId: Overload:ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.IsReferenced
  href: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.html#ParmaGIS_Modules_Parma_Space_Settings_CalcTableSettings_IsReferenced
  name: IsReferenced
  nameWithType: CalcTableSettings.IsReferenced
  fullName: ParmaGIS.Modules.Parma.Space.Settings.CalcTableSettings.IsReferenced
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
