### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
  commentId: N:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
  id: Viewmodels
  parent: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
  children:
  - ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels.ValueBridgeViewModel
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
  nameWithType: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.DataSpaceManagerTool
references:
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels.ValueBridgeViewModel
  commentId: T:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels.ValueBridgeViewModel
  href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels.ValueBridgeViewModel.html
  name: ValueBridgeViewModel
  nameWithType: ValueBridgeViewModel
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.Viewmodels.ValueBridgeViewModel
