### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.SettingsTool.Views
  commentId: N:ParmaGIS.WPF.Modules.SettingsTool.Views
  id: Views
  parent: ParmaGIS.WPF.Modules.SettingsTool
  children:
  - ParmaGIS.WPF.Modules.SettingsTool.Views.SettingsToolView
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.SettingsTool.Views
  nameWithType: ParmaGIS.WPF.Modules.SettingsTool.Views
  fullName: ParmaGIS.WPF.Modules.SettingsTool.Views
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.SettingsTool
references:
- uid: ParmaGIS.WPF.Modules.SettingsTool.Views.SettingsToolView
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.Views.SettingsToolView
  href: ParmaGIS.WPF.Modules.SettingsTool.Views.SettingsToolView.html
  name: SettingsToolView
  nameWithType: SettingsToolView
  fullName: ParmaGIS.WPF.Modules.SettingsTool.Views.SettingsToolView
