### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  commentId: N:ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  id: ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  children:
  - ParmaGIS.WPF.Modules.SettingsManagerTool.Views.SettingsTool
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  nameWithType: ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  fullName: ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.SettingsManagerTool
references:
- uid: ParmaGIS.WPF.Modules.SettingsManagerTool.Views.SettingsTool
  commentId: T:ParmaGIS.WPF.Modules.SettingsManagerTool.Views.SettingsTool
  href: ParmaGIS.WPF.Modules.SettingsManagerTool.Views.SettingsTool.html
  name: SettingsTool
  nameWithType: SettingsTool
  fullName: ParmaGIS.WPF.Modules.SettingsManagerTool.Views.SettingsTool
