### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Shell.Services.SettingsManagement.LolKek
  commentId: T:ParmaGIS.Shell.Services.SettingsManagement.LolKek
  id: LolKek
  parent: ParmaGIS.Shell.Services.SettingsManagement
  children:
  - ParmaGIS.Shell.Services.SettingsManagement.LolKek.Kek
  - ParmaGIS.Shell.Services.SettingsManagement.LolKek.Lol
  langs:
  - csharp
  - vb
  name: LolKek
  nameWithType: LolKek
  fullName: ParmaGIS.Shell.Services.SettingsManagement.LolKek
  type: Enum
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ShellSettingsPage.cs
      branch: origin/dev
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: LolKek
    path: ../../ParmaTest/common/src/ParmaGIS.Shell/Services/SettingsManagement/ShellSettingsPage.cs
    startLine: 4
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: public enum LolKek
    content.vb: Public Enum LolKek
- uid: ParmaGIS.Shell.Services.SettingsManagement.LolKek.Lol
  commentId: F:ParmaGIS.Shell.Services.SettingsManagement.LolKek.Lol
  id: Lol
  parent: ParmaGIS.Shell.Services.SettingsManagement.LolKek
  langs:
  - csharp
  - vb
  name: Lol
  nameWithType: LolKek.Lol
  fullName: ParmaGIS.Shell.Services.SettingsManagement.LolKek.Lol
  type: Field
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ShellSettingsPage.cs
      branch: origin/dev
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Lol
    path: ../../ParmaTest/common/src/ParmaGIS.Shell/Services/SettingsManagement/ShellSettingsPage.cs
    startLine: 6
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: Lol = 0
    return:
      type: ParmaGIS.Shell.Services.SettingsManagement.LolKek
- uid: ParmaGIS.Shell.Services.SettingsManagement.LolKek.Kek
  commentId: F:ParmaGIS.Shell.Services.SettingsManagement.LolKek.Kek
  id: Kek
  parent: ParmaGIS.Shell.Services.SettingsManagement.LolKek
  langs:
  - csharp
  - vb
  name: Kek
  nameWithType: LolKek.Kek
  fullName: ParmaGIS.Shell.Services.SettingsManagement.LolKek.Kek
  type: Field
  source:
    remote:
      path: common/src/ParmaGIS.Shell/Services/SettingsManagement/ShellSettingsPage.cs
      branch: origin/dev
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Kek
    path: ../../ParmaTest/common/src/ParmaGIS.Shell/Services/SettingsManagement/ShellSettingsPage.cs
    startLine: 7
  assemblies:
  - ParmaGIS.Shell
  namespace: ParmaGIS.Shell.Services.SettingsManagement
  syntax:
    content: Kek = 1
    return:
      type: ParmaGIS.Shell.Services.SettingsManagement.LolKek
references:
- uid: ParmaGIS.Shell.Services.SettingsManagement
  commentId: N:ParmaGIS.Shell.Services.SettingsManagement
  href: ParmaGIS.html
  name: ParmaGIS.Shell.Services.SettingsManagement
  nameWithType: ParmaGIS.Shell.Services.SettingsManagement
  fullName: ParmaGIS.Shell.Services.SettingsManagement
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Shell
    name: Shell
    href: ParmaGIS.Shell.html
  - name: .
  - uid: ParmaGIS.Shell.Services
    name: Services
    href: ParmaGIS.Shell.Services.html
  - name: .
  - uid: ParmaGIS.Shell.Services.SettingsManagement
    name: SettingsManagement
    href: ParmaGIS.Shell.Services.SettingsManagement.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Shell
    name: Shell
    href: ParmaGIS.Shell.html
  - name: .
  - uid: ParmaGIS.Shell.Services
    name: Services
    href: ParmaGIS.Shell.Services.html
  - name: .
  - uid: ParmaGIS.Shell.Services.SettingsManagement
    name: SettingsManagement
    href: ParmaGIS.Shell.Services.SettingsManagement.html
- uid: ParmaGIS.Shell.Services.SettingsManagement.LolKek
  commentId: T:ParmaGIS.Shell.Services.SettingsManagement.LolKek
  parent: ParmaGIS.Shell.Services.SettingsManagement
  href: ParmaGIS.Shell.Services.SettingsManagement.LolKek.html
  name: LolKek
  nameWithType: LolKek
  fullName: ParmaGIS.Shell.Services.SettingsManagement.LolKek
