### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.SettingsManagerTool
  commentId: N:ParmaGIS.WPF.Modules.SettingsManagerTool
  id: SettingsManagerTool
  parent: ParmaGIS.WPF.Modules
  children:
  - ParmaGIS.WPF.Modules.SettingsManagerTool.SettingsManagerToolModule
  - ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.SettingsManagerTool
  nameWithType: ParmaGIS.WPF.Modules.SettingsManagerTool
  fullName: ParmaGIS.WPF.Modules.SettingsManagerTool
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.SettingsManagerTool
references:
- uid: ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  commentId: N:ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  href: ParmaGIS.html
  name: ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  nameWithType: ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  fullName: ParmaGIS.WPF.Modules.SettingsManagerTool.Views
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsManagerTool
    name: SettingsManagerTool
    href: ParmaGIS.WPF.Modules.SettingsManagerTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsManagerTool.Views
    name: Views
    href: ParmaGIS.WPF.Modules.SettingsManagerTool.Views.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsManagerTool
    name: SettingsManagerTool
    href: ParmaGIS.WPF.Modules.SettingsManagerTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsManagerTool.Views
    name: Views
    href: ParmaGIS.WPF.Modules.SettingsManagerTool.Views.html
- uid: ParmaGIS.WPF.Modules.SettingsManagerTool.SettingsManagerToolModule
  commentId: T:ParmaGIS.WPF.Modules.SettingsManagerTool.SettingsManagerToolModule
  href: ParmaGIS.WPF.Modules.SettingsManagerTool.SettingsManagerToolModule.html
  name: SettingsManagerToolModule
  nameWithType: SettingsManagerToolModule
  fullName: ParmaGIS.WPF.Modules.SettingsManagerTool.SettingsManagerToolModule
