### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings
  commentId: N:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings
  id: CalcTableSettings
  parent: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views
  children:
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings.BonitetTableCardView
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings.StockTableCardView
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings
  nameWithType: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.Parma.UI
references:
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings.BonitetTableCardView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings.BonitetTableCardView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings.BonitetTableCardView.html
  name: BonitetTableCardView
  nameWithType: BonitetTableCardView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings.BonitetTableCardView
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings.StockTableCardView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings.StockTableCardView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings.StockTableCardView.html
  name: StockTableCardView
  nameWithType: StockTableCardView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CalcTableSettings.StockTableCardView
