### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Modules.Data.Space.Settings
  commentId: N:ParmaGIS.Modules.Data.Space.Settings
  id: Settings
  parent: ParmaGIS.Modules.Data.Space
  children:
  - ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
  - ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  - ParmaGIS.Modules.Data.Space.Settings.ISettingsRepository
  - ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace
  - ParmaGIS.Modules.Data.Space.Settings.SettingsRepositoryBase`2
  langs:
  - csharp
  - vb
  name: ParmaGIS.Modules.Data.Space.Settings
  nameWithType: ParmaGIS.Modules.Data.Space.Settings
  fullName: ParmaGIS.Modules.Data.Space.Settings
  type: Namespace
  assemblies:
  - ParmaGIS.Modules.Data
references:
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
  commentId: T:ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
  parent: ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsItem.html
  name: ISettingsItem
  nameWithType: ISettingsItem
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsItem
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  commentId: T:ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  parent: ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.html
  name: ISettingsRecord
  nameWithType: ISettingsRecord
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsRepository
  commentId: T:ParmaGIS.Modules.Data.Space.Settings.ISettingsRepository
  parent: ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsRepository.html
  name: ISettingsRepository
  nameWithType: ISettingsRepository
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsRepository
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace
  commentId: T:ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace
  parent: ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace.html
  name: ISettingsSpace
  nameWithType: ISettingsSpace
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsSpace
- uid: ParmaGIS.Modules.Data.Space.Settings.SettingsRepositoryBase`2
  commentId: T:ParmaGIS.Modules.Data.Space.Settings.SettingsRepositoryBase`2
  href: ParmaGIS.Modules.Data.Space.Settings.SettingsRepositoryBase-2.html
  name: SettingsRepositoryBase<TObjectId, TSettingsItem>
  nameWithType: SettingsRepositoryBase<TObjectId, TSettingsItem>
  fullName: ParmaGIS.Modules.Data.Space.Settings.SettingsRepositoryBase<TObjectId, TSettingsItem>
  nameWithType.vb: SettingsRepositoryBase(Of TObjectId, TSettingsItem)
  fullName.vb: ParmaGIS.Modules.Data.Space.Settings.SettingsRepositoryBase(Of TObjectId, TSettingsItem)
  name.vb: SettingsRepositoryBase(Of TObjectId, TSettingsItem)
  spec.csharp:
  - uid: ParmaGIS.Modules.Data.Space.Settings.SettingsRepositoryBase`2
    name: SettingsRepositoryBase
    href: ParmaGIS.Modules.Data.Space.Settings.SettingsRepositoryBase-2.html
  - name: <
  - name: TObjectId
  - name: ','
  - name: " "
  - name: TSettingsItem
  - name: '>'
  spec.vb:
  - uid: ParmaGIS.Modules.Data.Space.Settings.SettingsRepositoryBase`2
    name: SettingsRepositoryBase
    href: ParmaGIS.Modules.Data.Space.Settings.SettingsRepositoryBase-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TObjectId
  - name: ','
  - name: " "
  - name: TSettingsItem
  - name: )
- uid: ParmaGIS.Modules.Data.Space.Settings
  commentId: N:ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Modules.Data.Space.Settings
  nameWithType: ParmaGIS.Modules.Data.Space.Settings
  fullName: ParmaGIS.Modules.Data.Space.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
