### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord
  commentId: T:ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord
  id: SettingsRecord
  parent: ParmaGIS.Modules.Parma.Space.Settings
  children:
  - ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.#ctor
  - ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.Id
  - ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.ScopeId
  - ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.SubjectId
  langs:
  - csharp
  - vb
  name: SettingsRecord
  nameWithType: SettingsRecord
  fullName: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord
  type: Class
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/SettingsRecord.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: SettingsRecord
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/SettingsRecord.cs
    startLine: 9
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: 'public class SettingsRecord : ISettingsRecord'
    content.vb: Public Class SettingsRecord Implements ISettingsRecord
  inheritance:
  - System.Object
  implements:
  - ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.#ctor
  commentId: M:ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.#ctor
  id: '#ctor'
  parent: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord
  langs:
  - csharp
  - vb
  name: SettingsRecord()
  nameWithType: SettingsRecord.SettingsRecord()
  fullName: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.SettingsRecord()
  type: Constructor
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/SettingsRecord.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: .ctor
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/SettingsRecord.cs
    startLine: 11
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: public SettingsRecord()
    content.vb: Public Sub New()
  overload: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.#ctor*
  nameWithType.vb: SettingsRecord.New()
  fullName.vb: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.New()
  name.vb: New()
- uid: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.Id
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.Id
  id: Id
  parent: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: SettingsRecord.Id
  fullName: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.Id
  type: Property
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/SettingsRecord.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Id
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/SettingsRecord.cs
    startLine: 15
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: public Guid Id { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property Id As Guid
  overload: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.Id*
- uid: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.ScopeId
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.ScopeId
  id: ScopeId
  parent: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord
  langs:
  - csharp
  - vb
  name: ScopeId
  nameWithType: SettingsRecord.ScopeId
  fullName: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.ScopeId
  type: Property
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/SettingsRecord.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: ScopeId
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/SettingsRecord.cs
    startLine: 16
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: public Guid ScopeId { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property ScopeId As Guid
  overload: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.ScopeId*
- uid: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.SubjectId
  commentId: P:ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.SubjectId
  id: SubjectId
  parent: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord
  langs:
  - csharp
  - vb
  name: SubjectId
  nameWithType: SettingsRecord.SubjectId
  fullName: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.SubjectId
  type: Property
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Parma.Space/Settings/SettingsRecord.cs
      branch: origin/main
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: SubjectId
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Parma.Space/Settings/SettingsRecord.cs
    startLine: 17
  assemblies:
  - ParmaGIS.Modules.Parma.Space
  namespace: ParmaGIS.Modules.Parma.Space.Settings
  syntax:
    content: public Guid SubjectId { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property SubjectId As Guid
  overload: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.SubjectId*
references:
- uid: ParmaGIS.Modules.Parma.Space.Settings
  commentId: N:ParmaGIS.Modules.Parma.Space.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Modules.Parma.Space.Settings
  nameWithType: ParmaGIS.Modules.Parma.Space.Settings
  fullName: ParmaGIS.Modules.Parma.Space.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Parma
    name: Parma
    href: ParmaGIS.Modules.Parma.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space
    name: Space
    href: ParmaGIS.Modules.Parma.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Parma.Space.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Parma
    name: Parma
    href: ParmaGIS.Modules.Parma.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space
    name: Space
    href: ParmaGIS.Modules.Parma.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Parma.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Parma.Space.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  commentId: T:ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  parent: ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.html
  name: ISettingsRecord
  nameWithType: ISettingsRecord
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ParmaGIS.Modules.Data.Space.Settings
  commentId: N:ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Modules.Data.Space.Settings
  nameWithType: ParmaGIS.Modules.Data.Space.Settings
  fullName: ParmaGIS.Modules.Data.Space.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
- uid: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.#ctor*
  commentId: Overload:ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.#ctor
  href: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.html#ParmaGIS_Modules_Parma_Space_Settings_SettingsRecord__ctor
  name: SettingsRecord
  nameWithType: SettingsRecord.SettingsRecord
  fullName: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.SettingsRecord
  nameWithType.vb: SettingsRecord.New
  fullName.vb: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.New
  name.vb: New
- uid: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.Id*
  commentId: Overload:ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.Id
  href: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.html#ParmaGIS_Modules_Parma_Space_Settings_SettingsRecord_Id
  name: Id
  nameWithType: SettingsRecord.Id
  fullName: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.Id
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.ScopeId*
  commentId: Overload:ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.ScopeId
  href: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.html#ParmaGIS_Modules_Parma_Space_Settings_SettingsRecord_ScopeId
  name: ScopeId
  nameWithType: SettingsRecord.ScopeId
  fullName: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.ScopeId
- uid: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.SubjectId*
  commentId: Overload:ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.SubjectId
  href: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.html#ParmaGIS_Modules_Parma_Space_Settings_SettingsRecord_SubjectId
  name: SubjectId
  nameWithType: SettingsRecord.SubjectId
  fullName: ParmaGIS.Modules.Parma.Space.Settings.SettingsRecord.SubjectId
