### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Shell.Services.SettingsManagement
  commentId: N:ParmaGIS.Shell.Services.SettingsManagement
  id: SettingsManagement
  parent: ParmaGIS.Shell.Services
  children:
  - ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  langs:
  - csharp
  - vb
  name: ParmaGIS.Shell.Services.SettingsManagement
  nameWithType: ParmaGIS.Shell.Services.SettingsManagement
  fullName: ParmaGIS.Shell.Services.SettingsManagement
  type: Namespace
  assemblies:
  - ParmaGIS.Shell
references:
- uid: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  commentId: T:ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
  parent: ParmaGIS.Shell.Services.SettingsManagement
  href: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource.html
  name: ISettingsSource
  nameWithType: ISettingsSource
  fullName: ParmaGIS.Shell.Services.SettingsManagement.ISettingsSource
- uid: ParmaGIS.Shell.Services.SettingsManagement
  commentId: N:ParmaGIS.Shell.Services.SettingsManagement
  href: ParmaGIS.html
  name: ParmaGIS.Shell.Services.SettingsManagement
  nameWithType: ParmaGIS.Shell.Services.SettingsManagement
  fullName: ParmaGIS.Shell.Services.SettingsManagement
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Shell
    name: Shell
    href: ParmaGIS.Shell.html
  - name: .
  - uid: ParmaGIS.Shell.Services
    name: Services
    href: ParmaGIS.Shell.Services.html
  - name: .
  - uid: ParmaGIS.Shell.Services.SettingsManagement
    name: SettingsManagement
    href: ParmaGIS.Shell.Services.SettingsManagement.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Shell
    name: Shell
    href: ParmaGIS.Shell.html
  - name: .
  - uid: ParmaGIS.Shell.Services
    name: Services
    href: ParmaGIS.Shell.Services.html
  - name: .
  - uid: ParmaGIS.Shell.Services.SettingsManagement
    name: SettingsManagement
    href: ParmaGIS.Shell.Services.SettingsManagement.html
