### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.SettingsManagerTool
  commentId: N:ParmaGIS.WPF.Modules.SettingsManagerTool
  id: ParmaGIS.WPF.Modules.SettingsManagerTool
  children:
  - ParmaGIS.WPF.Modules.SettingsManagerTool.SettingsManagerToolModule
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.SettingsManagerTool
  nameWithType: ParmaGIS.WPF.Modules.SettingsManagerTool
  fullName: ParmaGIS.WPF.Modules.SettingsManagerTool
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.SettingsManagerTool
references:
- uid: ParmaGIS.WPF.Modules.SettingsManagerTool.SettingsManagerToolModule
  commentId: T:ParmaGIS.WPF.Modules.SettingsManagerTool.SettingsManagerToolModule
  href: ParmaGIS.WPF.Modules.SettingsManagerTool.SettingsManagerToolModule.html
  name: SettingsManagerToolModule
  nameWithType: SettingsManagerToolModule
  fullName: ParmaGIS.WPF.Modules.SettingsManagerTool.SettingsManagerToolModule
