### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Core.DAL.ISourceLayerConfigurator
  commentId: T:ParmaGIS.Core.DAL.ISourceLayerConfigurator
  id: ISourceLayerConfigurator
  parent: ParmaGIS.Core.DAL
  children:
  - ParmaGIS.Core.DAL.ISourceLayerConfigurator.Configure(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder)
  langs:
  - csharp
  - vb
  name: ISourceLayerConfigurator
  nameWithType: ISourceLayerConfigurator
  fullName: ParmaGIS.Core.DAL.ISourceLayerConfigurator
  type: Interface
  source:
    remote:
      path: common/src/ParmaGIS.Core.DAL/DataAccessLayer.cs
      branch: 337a82da41b4970cdcc7638dddfb6599823eb029
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: ISourceLayerConfigurator
    path: ../../ParmaTest/common/src/ParmaGIS.Core.DAL/DataAccessLayer.cs
    startLine: 9
  assemblies:
  - ParmaGIS.Core.DAL
  namespace: ParmaGIS.Core.DAL
  syntax:
    content: public interface ISourceLayerConfigurator
    content.vb: Public Interface ISourceLayerConfigurator
- uid: ParmaGIS.Core.DAL.ISourceLayerConfigurator.Configure(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder)
  commentId: M:ParmaGIS.Core.DAL.ISourceLayerConfigurator.Configure(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder)
  id: Configure(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder)
  parent: ParmaGIS.Core.DAL.ISourceLayerConfigurator
  langs:
  - csharp
  - vb
  name: Configure(DbContextOptionsBuilder)
  nameWithType: ISourceLayerConfigurator.Configure(DbContextOptionsBuilder)
  fullName: ParmaGIS.Core.DAL.ISourceLayerConfigurator.Configure(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Core.DAL/DataAccessLayer.cs
      branch: 337a82da41b4970cdcc7638dddfb6599823eb029
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Configure
    path: ../../ParmaTest/common/src/ParmaGIS.Core.DAL/DataAccessLayer.cs
    startLine: 11
  assemblies:
  - ParmaGIS.Core.DAL
  namespace: ParmaGIS.Core.DAL
  syntax:
    content: void Configure(DbContextOptionsBuilder optionsBuilder)
    parameters:
    - id: optionsBuilder
      type: Microsoft.EntityFrameworkCore.DbContextOptionsBuilder
    content.vb: Sub Configure(optionsBuilder As DbContextOptionsBuilder)
  overload: ParmaGIS.Core.DAL.ISourceLayerConfigurator.Configure*
references:
- uid: ParmaGIS.Core.DAL
  commentId: N:ParmaGIS.Core.DAL
  href: ParmaGIS.html
  name: ParmaGIS.Core.DAL
  nameWithType: ParmaGIS.Core.DAL
  fullName: ParmaGIS.Core.DAL
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.DAL
    name: DAL
    href: ParmaGIS.Core.DAL.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.DAL
    name: DAL
    href: ParmaGIS.Core.DAL.html
- uid: ParmaGIS.Core.DAL.ISourceLayerConfigurator.Configure*
  commentId: Overload:ParmaGIS.Core.DAL.ISourceLayerConfigurator.Configure
  href: ParmaGIS.Core.DAL.ISourceLayerConfigurator.html#ParmaGIS_Core_DAL_ISourceLayerConfigurator_Configure_Microsoft_EntityFrameworkCore_DbContextOptionsBuilder_
  name: Configure
  nameWithType: ISourceLayerConfigurator.Configure
  fullName: ParmaGIS.Core.DAL.ISourceLayerConfigurator.Configure
- uid: Microsoft.EntityFrameworkCore.DbContextOptionsBuilder
  commentId: T:Microsoft.EntityFrameworkCore.DbContextOptionsBuilder
  parent: Microsoft.EntityFrameworkCore
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder
  name: DbContextOptionsBuilder
  nameWithType: DbContextOptionsBuilder
  fullName: Microsoft.EntityFrameworkCore.DbContextOptionsBuilder
- uid: Microsoft.EntityFrameworkCore
  commentId: N:Microsoft.EntityFrameworkCore
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.EntityFrameworkCore
  nameWithType: Microsoft.EntityFrameworkCore
  fullName: Microsoft.EntityFrameworkCore
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.EntityFrameworkCore
    name: EntityFrameworkCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.entityframeworkcore
