### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  id: SettingsToolModule.ColorOptions
  parent: ParmaGIS.WPF.Modules.SettingsTool
  children:
  - ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Blue
  - ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Green
  - ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Red
  langs:
  - csharp
  - vb
  name: SettingsToolModule.ColorOptions
  nameWithType: SettingsToolModule.ColorOptions
  fullName: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  type: Enum
  source:
    remote:
      path: platforms/wpf/modules/ParmaGIS.WPF.Modules.SettingsTool/SettingsToolModule.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: ColorOptions
    path: ../ParmaGIS master/platforms/wpf/modules/ParmaGIS.WPF.Modules.SettingsTool/SettingsToolModule.cs
    startLine: 17
  assemblies:
  - ParmaGIS.WPF.Modules.SettingsTool
  namespace: ParmaGIS.WPF.Modules.SettingsTool
  syntax:
    content: public enum SettingsToolModule.ColorOptions
    content.vb: Public Enum SettingsToolModule.ColorOptions
- uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Red
  commentId: F:ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Red
  id: Red
  parent: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  langs:
  - csharp
  - vb
  name: Red
  nameWithType: SettingsToolModule.ColorOptions.Red
  fullName: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Red
  type: Field
  source:
    remote:
      path: platforms/wpf/modules/ParmaGIS.WPF.Modules.SettingsTool/SettingsToolModule.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Red
    path: ../ParmaGIS master/platforms/wpf/modules/ParmaGIS.WPF.Modules.SettingsTool/SettingsToolModule.cs
    startLine: 19
  assemblies:
  - ParmaGIS.WPF.Modules.SettingsTool
  namespace: ParmaGIS.WPF.Modules.SettingsTool
  syntax:
    content: Red = 0
    return:
      type: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
- uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Green
  commentId: F:ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Green
  id: Green
  parent: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  langs:
  - csharp
  - vb
  name: Green
  nameWithType: SettingsToolModule.ColorOptions.Green
  fullName: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Green
  type: Field
  source:
    remote:
      path: platforms/wpf/modules/ParmaGIS.WPF.Modules.SettingsTool/SettingsToolModule.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Green
    path: ../ParmaGIS master/platforms/wpf/modules/ParmaGIS.WPF.Modules.SettingsTool/SettingsToolModule.cs
    startLine: 20
  assemblies:
  - ParmaGIS.WPF.Modules.SettingsTool
  namespace: ParmaGIS.WPF.Modules.SettingsTool
  syntax:
    content: Green = 1
    return:
      type: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
- uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Blue
  commentId: F:ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Blue
  id: Blue
  parent: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  langs:
  - csharp
  - vb
  name: Blue
  nameWithType: SettingsToolModule.ColorOptions.Blue
  fullName: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.Blue
  type: Field
  source:
    remote:
      path: platforms/wpf/modules/ParmaGIS.WPF.Modules.SettingsTool/SettingsToolModule.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Blue
    path: ../ParmaGIS master/platforms/wpf/modules/ParmaGIS.WPF.Modules.SettingsTool/SettingsToolModule.cs
    startLine: 21
  assemblies:
  - ParmaGIS.WPF.Modules.SettingsTool
  namespace: ParmaGIS.WPF.Modules.SettingsTool
  syntax:
    content: Blue = 2
    return:
      type: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
references:
- uid: ParmaGIS.WPF.Modules.SettingsTool
  commentId: N:ParmaGIS.WPF.Modules.SettingsTool
  href: ParmaGIS.html
  name: ParmaGIS.WPF.Modules.SettingsTool
  nameWithType: ParmaGIS.WPF.Modules.SettingsTool
  fullName: ParmaGIS.WPF.Modules.SettingsTool
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
- uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  parent: ParmaGIS.WPF.Modules.SettingsTool
  href: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.html
  name: SettingsToolModule.ColorOptions
  nameWithType: SettingsToolModule.ColorOptions
  fullName: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  spec.csharp:
  - uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule
    name: SettingsToolModule
    href: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
    name: ColorOptions
    href: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.html
  spec.vb:
  - uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule
    name: SettingsToolModule
    href: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
    name: ColorOptions
    href: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.html
