### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.SettingsTool.Pipelines
  commentId: N:ParmaGIS.WPF.Modules.SettingsTool.Pipelines
  id: Pipelines
  parent: ParmaGIS.WPF.Modules.SettingsTool
  children:
  - ParmaGIS.WPF.Modules.SettingsTool.Pipelines.ViewModelMagistral
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.SettingsTool.Pipelines
  nameWithType: ParmaGIS.WPF.Modules.SettingsTool.Pipelines
  fullName: ParmaGIS.WPF.Modules.SettingsTool.Pipelines
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.SettingsTool
references:
- uid: ParmaGIS.WPF.Modules.SettingsTool.Pipelines.ViewModelMagistral
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.Pipelines.ViewModelMagistral
  href: ParmaGIS.WPF.Modules.SettingsTool.Pipelines.ViewModelMagistral.html
  name: ViewModelMagistral
  nameWithType: ViewModelMagistral
  fullName: ParmaGIS.WPF.Modules.SettingsTool.Pipelines.ViewModelMagistral
