### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  commentId: T:ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  id: ISettingsRecord
  parent: ParmaGIS.Modules.Data.Space.Settings
  children:
  - ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.Id
  - ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.ScopeId
  - ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.SubjectId
  langs:
  - csharp
  - vb
  name: ISettingsRecord
  nameWithType: ISettingsRecord
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  type: Interface
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsRecord.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: ISettingsRecord
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsRecord.cs
    startLine: 5
  assemblies:
  - ParmaGIS.Modules.Data
  namespace: ParmaGIS.Modules.Data.Space.Settings
  summary: Представляет запись настроек.
  example: []
  syntax:
    content: public interface ISettingsRecord
    content.vb: Public Interface ISettingsRecord
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.Id
  commentId: P:ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.Id
  id: Id
  parent: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: ISettingsRecord.Id
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.Id
  type: Property
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsRecord.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: Id
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsRecord.cs
    startLine: 10
  assemblies:
  - ParmaGIS.Modules.Data
  namespace: ParmaGIS.Modules.Data.Space.Settings
  summary: Возвращает уникальный идентификатор записи настроек.
  example: []
  syntax:
    content: object Id { get; }
    parameters: []
    return:
      type: System.Object
    content.vb: ReadOnly Property Id As Object
  overload: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.Id*
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.ScopeId
  commentId: P:ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.ScopeId
  id: ScopeId
  parent: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  langs:
  - csharp
  - vb
  name: ScopeId
  nameWithType: ISettingsRecord.ScopeId
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.ScopeId
  type: Property
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsRecord.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: ScopeId
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsRecord.cs
    startLine: 15
  assemblies:
  - ParmaGIS.Modules.Data
  namespace: ParmaGIS.Modules.Data.Space.Settings
  summary: Возвращает уникальный идентификатор области действия настроек.
  example: []
  syntax:
    content: object ScopeId { get; }
    parameters: []
    return:
      type: System.Object
    content.vb: ReadOnly Property ScopeId As Object
  overload: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.ScopeId*
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.SubjectId
  commentId: P:ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.SubjectId
  id: SubjectId
  parent: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord
  langs:
  - csharp
  - vb
  name: SubjectId
  nameWithType: ISettingsRecord.SubjectId
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.SubjectId
  type: Property
  source:
    remote:
      path: common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsRecord.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: SubjectId
    path: ../ParmaGIS master/common/modules/ParmaGIS.Modules.Data/Space/Settings/ISettingsRecord.cs
    startLine: 20
  assemblies:
  - ParmaGIS.Modules.Data
  namespace: ParmaGIS.Modules.Data.Space.Settings
  summary: Возвращает уникальный идентификатор субъекта.
  example: []
  syntax:
    content: object SubjectId { get; }
    parameters: []
    return:
      type: System.Object
    content.vb: ReadOnly Property SubjectId As Object
  overload: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.SubjectId*
references:
- uid: ParmaGIS.Modules.Data.Space.Settings
  commentId: N:ParmaGIS.Modules.Data.Space.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Modules.Data.Space.Settings
  nameWithType: ParmaGIS.Modules.Data.Space.Settings
  fullName: ParmaGIS.Modules.Data.Space.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Modules
    name: Modules
    href: ParmaGIS.Modules.html
  - name: .
  - uid: ParmaGIS.Modules.Data
    name: Data
    href: ParmaGIS.Modules.Data.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space
    name: Space
    href: ParmaGIS.Modules.Data.Space.html
  - name: .
  - uid: ParmaGIS.Modules.Data.Space.Settings
    name: Settings
    href: ParmaGIS.Modules.Data.Space.Settings.html
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.Id*
  commentId: Overload:ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.Id
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.html#ParmaGIS_Modules_Data_Space_Settings_ISettingsRecord_Id
  name: Id
  nameWithType: ISettingsRecord.Id
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.Id
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.ScopeId*
  commentId: Overload:ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.ScopeId
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.html#ParmaGIS_Modules_Data_Space_Settings_ISettingsRecord_ScopeId
  name: ScopeId
  nameWithType: ISettingsRecord.ScopeId
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.ScopeId
- uid: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.SubjectId*
  commentId: Overload:ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.SubjectId
  href: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.html#ParmaGIS_Modules_Data_Space_Settings_ISettingsRecord_SubjectId
  name: SubjectId
  nameWithType: ISettingsRecord.SubjectId
  fullName: ParmaGIS.Modules.Data.Space.Settings.ISettingsRecord.SubjectId
