### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Core.Modularity.ConfigurationExtensions
  commentId: T:ParmaGIS.Core.Modularity.ConfigurationExtensions
  id: ConfigurationExtensions
  parent: ParmaGIS.Core.Modularity
  children:
  - ParmaGIS.Core.Modularity.ConfigurationExtensions.GetModulesDirectory(ParmaGIS.Core.Shell.Configuration)
  - ParmaGIS.Core.Modularity.ConfigurationExtensions.SetModulesDirectory(ParmaGIS.Core.Shell.Configuration,System.String)
  langs:
  - csharp
  - vb
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: ParmaGIS.Core.Modularity.ConfigurationExtensions
  type: Class
  source:
    remote:
      path: common/src/ParmaGIS.Core/Modularity/ConfigurationExtensions.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: ConfigurationExtensions
    path: ../ParmaGIS master/common/src/ParmaGIS.Core/Modularity/ConfigurationExtensions.cs
    startLine: 7
  assemblies:
  - ParmaGIS.Core
  namespace: ParmaGIS.Core.Modularity
  summary: Расширения для конфигурации <xref href="ParmaGIS.Core.Shell.Configuration" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static class ConfigurationExtensions
    content.vb: Public Module ConfigurationExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: ParmaGIS.Core.Modularity.ConfigurationExtensions.SetModulesDirectory(ParmaGIS.Core.Shell.Configuration,System.String)
  commentId: M:ParmaGIS.Core.Modularity.ConfigurationExtensions.SetModulesDirectory(ParmaGIS.Core.Shell.Configuration,System.String)
  id: SetModulesDirectory(ParmaGIS.Core.Shell.Configuration,System.String)
  isExtensionMethod: true
  parent: ParmaGIS.Core.Modularity.ConfigurationExtensions
  langs:
  - csharp
  - vb
  name: SetModulesDirectory(Configuration, string)
  nameWithType: ConfigurationExtensions.SetModulesDirectory(Configuration, string)
  fullName: ParmaGIS.Core.Modularity.ConfigurationExtensions.SetModulesDirectory(ParmaGIS.Core.Shell.Configuration, string)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Core/Modularity/ConfigurationExtensions.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: SetModulesDirectory
    path: ../ParmaGIS master/common/src/ParmaGIS.Core/Modularity/ConfigurationExtensions.cs
    startLine: 16
  assemblies:
  - ParmaGIS.Core
  namespace: ParmaGIS.Core.Modularity
  summary: Задает путь до папки с модулями.
  example: []
  syntax:
    content: public static void SetModulesDirectory(this Configuration configuration, string modulesDirecotry)
    parameters:
    - id: configuration
      type: ParmaGIS.Core.Shell.Configuration
      description: Конфигурация.
    - id: modulesDirecotry
      type: System.String
      description: Директория, в которой находятся модули.
    content.vb: Public Shared Sub SetModulesDirectory(configuration As Configuration, modulesDirecotry As String)
  overload: ParmaGIS.Core.Modularity.ConfigurationExtensions.SetModulesDirectory*
  nameWithType.vb: ConfigurationExtensions.SetModulesDirectory(Configuration, String)
  fullName.vb: ParmaGIS.Core.Modularity.ConfigurationExtensions.SetModulesDirectory(ParmaGIS.Core.Shell.Configuration, String)
  name.vb: SetModulesDirectory(Configuration, String)
- uid: ParmaGIS.Core.Modularity.ConfigurationExtensions.GetModulesDirectory(ParmaGIS.Core.Shell.Configuration)
  commentId: M:ParmaGIS.Core.Modularity.ConfigurationExtensions.GetModulesDirectory(ParmaGIS.Core.Shell.Configuration)
  id: GetModulesDirectory(ParmaGIS.Core.Shell.Configuration)
  isExtensionMethod: true
  parent: ParmaGIS.Core.Modularity.ConfigurationExtensions
  langs:
  - csharp
  - vb
  name: GetModulesDirectory(Configuration)
  nameWithType: ConfigurationExtensions.GetModulesDirectory(Configuration)
  fullName: ParmaGIS.Core.Modularity.ConfigurationExtensions.GetModulesDirectory(ParmaGIS.Core.Shell.Configuration)
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Core/Modularity/ConfigurationExtensions.cs
      branch: origin/test
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: GetModulesDirectory
    path: ../ParmaGIS master/common/src/ParmaGIS.Core/Modularity/ConfigurationExtensions.cs
    startLine: 26
  assemblies:
  - ParmaGIS.Core
  namespace: ParmaGIS.Core.Modularity
  summary: Возвращает путь до папки с модулями.
  example: []
  syntax:
    content: public static string? GetModulesDirectory(this Configuration config)
    parameters:
    - id: config
      type: ParmaGIS.Core.Shell.Configuration
      description: Конфигурация.
    return:
      type: System.String
      description: Путь до папки с модулями.
    content.vb: Public Shared Function GetModulesDirectory(config As Configuration) As String
  overload: ParmaGIS.Core.Modularity.ConfigurationExtensions.GetModulesDirectory*
references:
- uid: ParmaGIS.Core.Shell.Configuration
  commentId: T:ParmaGIS.Core.Shell.Configuration
  parent: ParmaGIS.Core.Shell
  href: ParmaGIS.Core.Shell.Configuration.html
  name: Configuration
  nameWithType: Configuration
  fullName: ParmaGIS.Core.Shell.Configuration
- uid: ParmaGIS.Core.Modularity
  commentId: N:ParmaGIS.Core.Modularity
  href: ParmaGIS.html
  name: ParmaGIS.Core.Modularity
  nameWithType: ParmaGIS.Core.Modularity
  fullName: ParmaGIS.Core.Modularity
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.Modularity
    name: Modularity
    href: ParmaGIS.Core.Modularity.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.Modularity
    name: Modularity
    href: ParmaGIS.Core.Modularity.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: ParmaGIS.Core.Shell
  commentId: N:ParmaGIS.Core.Shell
  href: ParmaGIS.html
  name: ParmaGIS.Core.Shell
  nameWithType: ParmaGIS.Core.Shell
  fullName: ParmaGIS.Core.Shell
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.Shell
    name: Shell
    href: ParmaGIS.Core.Shell.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.Shell
    name: Shell
    href: ParmaGIS.Core.Shell.html
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ParmaGIS.Core.Modularity.ConfigurationExtensions.SetModulesDirectory*
  commentId: Overload:ParmaGIS.Core.Modularity.ConfigurationExtensions.SetModulesDirectory
  href: ParmaGIS.Core.Modularity.ConfigurationExtensions.html#ParmaGIS_Core_Modularity_ConfigurationExtensions_SetModulesDirectory_ParmaGIS_Core_Shell_Configuration_System_String_
  name: SetModulesDirectory
  nameWithType: ConfigurationExtensions.SetModulesDirectory
  fullName: ParmaGIS.Core.Modularity.ConfigurationExtensions.SetModulesDirectory
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ParmaGIS.Core.Modularity.ConfigurationExtensions.GetModulesDirectory*
  commentId: Overload:ParmaGIS.Core.Modularity.ConfigurationExtensions.GetModulesDirectory
  href: ParmaGIS.Core.Modularity.ConfigurationExtensions.html#ParmaGIS_Core_Modularity_ConfigurationExtensions_GetModulesDirectory_ParmaGIS_Core_Shell_Configuration_
  name: GetModulesDirectory
  nameWithType: ConfigurationExtensions.GetModulesDirectory
  fullName: ParmaGIS.Core.Modularity.ConfigurationExtensions.GetModulesDirectory
