### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
  commentId: N:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
  id: ViewModels
  parent: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows
  children:
  - ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.BridgeSettingsViewModel
  - ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.EntityBridgeViewModel
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
  nameWithType: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.DataSpaceManagerTool
references:
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.BridgeSettingsViewModel
  commentId: T:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.BridgeSettingsViewModel
  href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.BridgeSettingsViewModel.html
  name: BridgeSettingsViewModel
  nameWithType: BridgeSettingsViewModel
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.BridgeSettingsViewModel
- uid: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.EntityBridgeViewModel
  commentId: T:ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.EntityBridgeViewModel
  href: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.EntityBridgeViewModel.html
  name: EntityBridgeViewModel
  nameWithType: EntityBridgeViewModel
  fullName: ParmaGIS.WPF.Modules.DataSpaceManagerTool.DataSpaceMasters.BridgeSettingsWindows.ViewModels.EntityBridgeViewModel
