### YamlMime:ManagedReference
items:
- uid: ParmaGIS.Core.UI.Settings.ISettingsManager
  commentId: T:ParmaGIS.Core.UI.Settings.ISettingsManager
  id: ISettingsManager
  parent: ParmaGIS.Core.UI.Settings
  children:
  - ParmaGIS.Core.UI.Settings.ISettingsManager.GetProvider``1
  langs:
  - csharp
  - vb
  name: ISettingsManager
  nameWithType: ISettingsManager
  fullName: ParmaGIS.Core.UI.Settings.ISettingsManager
  type: Interface
  source:
    remote:
      path: common/src/ParmaGIS.Core.UI/Settings/ISettingsManager.cs
      branch: 337a82da41b4970cdcc7638dddfb6599823eb029
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: ISettingsManager
    path: ../../ParmaTest/common/src/ParmaGIS.Core.UI/Settings/ISettingsManager.cs
    startLine: 4
  assemblies:
  - ParmaGIS.Core.UI
  namespace: ParmaGIS.Core.UI.Settings
  syntax:
    content: 'public interface ISettingsManager : IParameterGiver'
    content.vb: Public Interface ISettingsManager Inherits IParameterGiver
  inheritedMembers:
  - ParmaGIS.Core.Serviceability.IParameterGiver.ParameterType
  - ParmaGIS.Core.Serviceability.IParameterGiver.GetParameter(System.Type,System.Type)
- uid: ParmaGIS.Core.UI.Settings.ISettingsManager.GetProvider``1
  commentId: M:ParmaGIS.Core.UI.Settings.ISettingsManager.GetProvider``1
  id: GetProvider``1
  parent: ParmaGIS.Core.UI.Settings.ISettingsManager
  langs:
  - csharp
  - vb
  name: GetProvider<TPage>()
  nameWithType: ISettingsManager.GetProvider<TPage>()
  fullName: ParmaGIS.Core.UI.Settings.ISettingsManager.GetProvider<TPage>()
  type: Method
  source:
    remote:
      path: common/src/ParmaGIS.Core.UI/Settings/ISettingsManager.cs
      branch: 337a82da41b4970cdcc7638dddfb6599823eb029
      repo: https://github.com/ParmaGIS/ParmaGIS.Net.git
    id: GetProvider
    path: ../../ParmaTest/common/src/ParmaGIS.Core.UI/Settings/ISettingsManager.cs
    startLine: 6
  assemblies:
  - ParmaGIS.Core.UI
  namespace: ParmaGIS.Core.UI.Settings
  syntax:
    content: 'SettingsProvider<TPage>? GetProvider<TPage>() where TPage : SettingsPage'
    typeParameters:
    - id: TPage
    return:
      type: ParmaGIS.Core.UI.Settings.SettingsProvider{{TPage}}
    content.vb: Function GetProvider(Of TPage As SettingsPage)() As SettingsProvider(Of TPage)
  overload: ParmaGIS.Core.UI.Settings.ISettingsManager.GetProvider*
  nameWithType.vb: ISettingsManager.GetProvider(Of TPage)()
  fullName.vb: ParmaGIS.Core.UI.Settings.ISettingsManager.GetProvider(Of TPage)()
  name.vb: GetProvider(Of TPage)()
references:
- uid: ParmaGIS.Core.UI.Settings
  commentId: N:ParmaGIS.Core.UI.Settings
  href: ParmaGIS.html
  name: ParmaGIS.Core.UI.Settings
  nameWithType: ParmaGIS.Core.UI.Settings
  fullName: ParmaGIS.Core.UI.Settings
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.UI
    name: UI
    href: ParmaGIS.Core.UI.html
  - name: .
  - uid: ParmaGIS.Core.UI.Settings
    name: Settings
    href: ParmaGIS.Core.UI.Settings.html
- uid: ParmaGIS.Core.Serviceability.IParameterGiver.ParameterType
  commentId: P:ParmaGIS.Core.Serviceability.IParameterGiver.ParameterType
  parent: ParmaGIS.Core.Serviceability.IParameterGiver
  href: ParmaGIS.Core.Serviceability.IParameterGiver.html#ParmaGIS_Core_Serviceability_IParameterGiver_ParameterType
  name: ParameterType
  nameWithType: IParameterGiver.ParameterType
  fullName: ParmaGIS.Core.Serviceability.IParameterGiver.ParameterType
- uid: ParmaGIS.Core.Serviceability.IParameterGiver.GetParameter(System.Type,System.Type)
  commentId: M:ParmaGIS.Core.Serviceability.IParameterGiver.GetParameter(System.Type,System.Type)
  parent: ParmaGIS.Core.Serviceability.IParameterGiver
  isExternal: true
  href: ParmaGIS.Core.Serviceability.IParameterGiver.html#ParmaGIS_Core_Serviceability_IParameterGiver_GetParameter_System_Type_System_Type_
  name: GetParameter(Type, Type)
  nameWithType: IParameterGiver.GetParameter(Type, Type)
  fullName: ParmaGIS.Core.Serviceability.IParameterGiver.GetParameter(System.Type, System.Type)
  spec.csharp:
  - uid: ParmaGIS.Core.Serviceability.IParameterGiver.GetParameter(System.Type,System.Type)
    name: GetParameter
    href: ParmaGIS.Core.Serviceability.IParameterGiver.html#ParmaGIS_Core_Serviceability_IParameterGiver_GetParameter_System_Type_System_Type_
  - name: (
  - uid: System.Type
    name: Type
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.type
  - name: ','
  - name: " "
  - uid: System.Type
    name: Type
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.type
  - name: )
  spec.vb:
  - uid: ParmaGIS.Core.Serviceability.IParameterGiver.GetParameter(System.Type,System.Type)
    name: GetParameter
    href: ParmaGIS.Core.Serviceability.IParameterGiver.html#ParmaGIS_Core_Serviceability_IParameterGiver_GetParameter_System_Type_System_Type_
  - name: (
  - uid: System.Type
    name: Type
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.type
  - name: ','
  - name: " "
  - uid: System.Type
    name: Type
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.type
  - name: )
- uid: ParmaGIS.Core.Serviceability.IParameterGiver
  commentId: T:ParmaGIS.Core.Serviceability.IParameterGiver
  parent: ParmaGIS.Core.Serviceability
  href: ParmaGIS.Core.Serviceability.IParameterGiver.html
  name: IParameterGiver
  nameWithType: IParameterGiver
  fullName: ParmaGIS.Core.Serviceability.IParameterGiver
- uid: ParmaGIS.Core.Serviceability
  commentId: N:ParmaGIS.Core.Serviceability
  href: ParmaGIS.html
  name: ParmaGIS.Core.Serviceability
  nameWithType: ParmaGIS.Core.Serviceability
  fullName: ParmaGIS.Core.Serviceability
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.Serviceability
    name: Serviceability
    href: ParmaGIS.Core.Serviceability.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.Core
    name: Core
    href: ParmaGIS.Core.html
  - name: .
  - uid: ParmaGIS.Core.Serviceability
    name: Serviceability
    href: ParmaGIS.Core.Serviceability.html
- uid: ParmaGIS.Core.UI.Settings.ISettingsManager.GetProvider*
  commentId: Overload:ParmaGIS.Core.UI.Settings.ISettingsManager.GetProvider
  href: ParmaGIS.Core.UI.Settings.ISettingsManager.html#ParmaGIS_Core_UI_Settings_ISettingsManager_GetProvider__1
  name: GetProvider
  nameWithType: ISettingsManager.GetProvider
  fullName: ParmaGIS.Core.UI.Settings.ISettingsManager.GetProvider
- uid: ParmaGIS.Core.UI.Settings.SettingsProvider{{TPage}}
  commentId: T:ParmaGIS.Core.UI.Settings.SettingsProvider{``0}
  parent: ParmaGIS.Core.UI.Settings
  definition: ParmaGIS.Core.UI.Settings.SettingsProvider`1
  href: ParmaGIS.Core.UI.Settings.SettingsProvider-1.html
  name: SettingsProvider<TPage>
  nameWithType: SettingsProvider<TPage>
  fullName: ParmaGIS.Core.UI.Settings.SettingsProvider<TPage>
  nameWithType.vb: SettingsProvider(Of TPage)
  fullName.vb: ParmaGIS.Core.UI.Settings.SettingsProvider(Of TPage)
  name.vb: SettingsProvider(Of TPage)
  spec.csharp:
  - uid: ParmaGIS.Core.UI.Settings.SettingsProvider`1
    name: SettingsProvider
    href: ParmaGIS.Core.UI.Settings.SettingsProvider-1.html
  - name: <
  - name: TPage
  - name: '>'
  spec.vb:
  - uid: ParmaGIS.Core.UI.Settings.SettingsProvider`1
    name: SettingsProvider
    href: ParmaGIS.Core.UI.Settings.SettingsProvider-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TPage
  - name: )
- uid: ParmaGIS.Core.UI.Settings.SettingsProvider`1
  commentId: T:ParmaGIS.Core.UI.Settings.SettingsProvider`1
  href: ParmaGIS.Core.UI.Settings.SettingsProvider-1.html
  name: SettingsProvider<T>
  nameWithType: SettingsProvider<T>
  fullName: ParmaGIS.Core.UI.Settings.SettingsProvider<T>
  nameWithType.vb: SettingsProvider(Of T)
  fullName.vb: ParmaGIS.Core.UI.Settings.SettingsProvider(Of T)
  name.vb: SettingsProvider(Of T)
  spec.csharp:
  - uid: ParmaGIS.Core.UI.Settings.SettingsProvider`1
    name: SettingsProvider
    href: ParmaGIS.Core.UI.Settings.SettingsProvider-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: ParmaGIS.Core.UI.Settings.SettingsProvider`1
    name: SettingsProvider
    href: ParmaGIS.Core.UI.Settings.SettingsProvider-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
