### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  commentId: N:ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  id: ViewModels
  parent: ParmaGIS.WPF.Modules.SettingsTool
  children:
  - ParmaGIS.WPF.Modules.SettingsTool.ViewModels.CheckInputViewModel
  - ParmaGIS.WPF.Modules.SettingsTool.ViewModels.DoubleInputViewModel
  - ParmaGIS.WPF.Modules.SettingsTool.ViewModels.InputViewModelBase
  - ParmaGIS.WPF.Modules.SettingsTool.ViewModels.IntInputViewModel
  - ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SelectInputViewModel
  - ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SettingViewModel
  - ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SettingsParameterGroupViewModel
  - ParmaGIS.WPF.Modules.SettingsTool.ViewModels.StringInputViewModel
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  nameWithType: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  fullName: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.SettingsTool
references:
- uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.CheckInputViewModel
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.ViewModels.CheckInputViewModel
  href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.CheckInputViewModel.html
  name: CheckInputViewModel
  nameWithType: CheckInputViewModel
  fullName: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.CheckInputViewModel
- uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.DoubleInputViewModel
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.ViewModels.DoubleInputViewModel
  href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.DoubleInputViewModel.html
  name: DoubleInputViewModel
  nameWithType: DoubleInputViewModel
  fullName: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.DoubleInputViewModel
- uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.InputViewModelBase
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.ViewModels.InputViewModelBase
  parent: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.InputViewModelBase.html
  name: InputViewModelBase
  nameWithType: InputViewModelBase
  fullName: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.InputViewModelBase
- uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.IntInputViewModel
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.ViewModels.IntInputViewModel
  href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.IntInputViewModel.html
  name: IntInputViewModel
  nameWithType: IntInputViewModel
  fullName: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.IntInputViewModel
- uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SelectInputViewModel
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SelectInputViewModel
  href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SelectInputViewModel.html
  name: SelectInputViewModel
  nameWithType: SelectInputViewModel
  fullName: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SelectInputViewModel
- uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SettingViewModel
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SettingViewModel
  href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SettingViewModel.html
  name: SettingViewModel
  nameWithType: SettingViewModel
  fullName: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SettingViewModel
- uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SettingsParameterGroupViewModel
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SettingsParameterGroupViewModel
  href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SettingsParameterGroupViewModel.html
  name: SettingsParameterGroupViewModel
  nameWithType: SettingsParameterGroupViewModel
  fullName: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.SettingsParameterGroupViewModel
- uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.StringInputViewModel
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.ViewModels.StringInputViewModel
  href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.StringInputViewModel.html
  name: StringInputViewModel
  nameWithType: StringInputViewModel
  fullName: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.StringInputViewModel
- uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  commentId: N:ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  href: ParmaGIS.html
  name: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  nameWithType: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  fullName: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
    name: ViewModels
    href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
    name: ViewModels
    href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.html
