### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.SettingsTool
  commentId: N:ParmaGIS.WPF.Modules.SettingsTool
  id: SettingsTool
  parent: ParmaGIS.WPF.Modules
  children:
  - ParmaGIS.WPF.Modules.SettingsTool.IInputViewModel
  - ParmaGIS.WPF.Modules.SettingsTool.Pipelines
  - ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule
  - ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  - ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  - ParmaGIS.WPF.Modules.SettingsTool.Views
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.SettingsTool
  nameWithType: ParmaGIS.WPF.Modules.SettingsTool
  fullName: ParmaGIS.WPF.Modules.SettingsTool
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.SettingsTool
references:
- uid: ParmaGIS.WPF.Modules.SettingsTool.Pipelines
  commentId: N:ParmaGIS.WPF.Modules.SettingsTool.Pipelines
  href: ParmaGIS.html
  name: ParmaGIS.WPF.Modules.SettingsTool.Pipelines
  nameWithType: ParmaGIS.WPF.Modules.SettingsTool.Pipelines
  fullName: ParmaGIS.WPF.Modules.SettingsTool.Pipelines
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.Pipelines
    name: Pipelines
    href: ParmaGIS.WPF.Modules.SettingsTool.Pipelines.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.Pipelines
    name: Pipelines
    href: ParmaGIS.WPF.Modules.SettingsTool.Pipelines.html
- uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  commentId: N:ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  href: ParmaGIS.html
  name: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  nameWithType: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  fullName: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
    name: ViewModels
    href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.ViewModels
    name: ViewModels
    href: ParmaGIS.WPF.Modules.SettingsTool.ViewModels.html
- uid: ParmaGIS.WPF.Modules.SettingsTool.Views
  commentId: N:ParmaGIS.WPF.Modules.SettingsTool.Views
  href: ParmaGIS.html
  name: ParmaGIS.WPF.Modules.SettingsTool.Views
  nameWithType: ParmaGIS.WPF.Modules.SettingsTool.Views
  fullName: ParmaGIS.WPF.Modules.SettingsTool.Views
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.Views
    name: Views
    href: ParmaGIS.WPF.Modules.SettingsTool.Views.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.Views
    name: Views
    href: ParmaGIS.WPF.Modules.SettingsTool.Views.html
- uid: ParmaGIS.WPF.Modules.SettingsTool.IInputViewModel
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.IInputViewModel
  parent: ParmaGIS.WPF.Modules.SettingsTool
  href: ParmaGIS.WPF.Modules.SettingsTool.IInputViewModel.html
  name: IInputViewModel
  nameWithType: IInputViewModel
  fullName: ParmaGIS.WPF.Modules.SettingsTool.IInputViewModel
- uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule
  href: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.html
  name: SettingsToolModule
  nameWithType: SettingsToolModule
  fullName: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule
- uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  commentId: T:ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  parent: ParmaGIS.WPF.Modules.SettingsTool
  href: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.html
  name: SettingsToolModule.ColorOptions
  nameWithType: SettingsToolModule.ColorOptions
  fullName: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
  spec.csharp:
  - uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule
    name: SettingsToolModule
    href: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
    name: ColorOptions
    href: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.html
  spec.vb:
  - uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule
    name: SettingsToolModule
    href: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions
    name: ColorOptions
    href: ParmaGIS.WPF.Modules.SettingsTool.SettingsToolModule.ColorOptions.html
- uid: ParmaGIS.WPF.Modules.SettingsTool
  commentId: N:ParmaGIS.WPF.Modules.SettingsTool
  href: ParmaGIS.html
  name: ParmaGIS.WPF.Modules.SettingsTool
  nameWithType: ParmaGIS.WPF.Modules.SettingsTool
  fullName: ParmaGIS.WPF.Modules.SettingsTool
  spec.csharp:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
  spec.vb:
  - uid: ParmaGIS
    name: ParmaGIS
    href: ParmaGIS.html
  - name: .
  - uid: ParmaGIS.WPF
    name: WPF
    href: ParmaGIS.WPF.html
  - name: .
  - uid: ParmaGIS.WPF.Modules
    name: Modules
    href: ParmaGIS.WPF.Modules.html
  - name: .
  - uid: ParmaGIS.WPF.Modules.SettingsTool
    name: SettingsTool
    href: ParmaGIS.WPF.Modules.SettingsTool.html
