### YamlMime:ManagedReference
items:
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings
  commentId: N:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings
  id: CatalogSettings
  parent: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views
  children:
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.BonitetClassSettingsCardView
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.DefaultCatalogSettingsCardView
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.MunicipalAreaSettingsCardView
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.OrganizationSettingsCardView
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.OriginSettingsCardView
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TaxatorSettingsCardView
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TreeSpeciesSettingsCardView
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TreeSpeciesTypeSettingsCardView
  - ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.UnitMeasureSettingsCardView
  langs:
  - csharp
  - vb
  name: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings
  nameWithType: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings
  type: Namespace
  assemblies:
  - ParmaGIS.WPF.Modules.Parma.UI
references:
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.BonitetClassSettingsCardView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.BonitetClassSettingsCardView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.BonitetClassSettingsCardView.html
  name: BonitetClassSettingsCardView
  nameWithType: BonitetClassSettingsCardView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.BonitetClassSettingsCardView
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.DefaultCatalogSettingsCardView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.DefaultCatalogSettingsCardView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.DefaultCatalogSettingsCardView.html
  name: DefaultCatalogSettingsCardView
  nameWithType: DefaultCatalogSettingsCardView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.DefaultCatalogSettingsCardView
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.MunicipalAreaSettingsCardView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.MunicipalAreaSettingsCardView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.MunicipalAreaSettingsCardView.html
  name: MunicipalAreaSettingsCardView
  nameWithType: MunicipalAreaSettingsCardView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.MunicipalAreaSettingsCardView
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.OrganizationSettingsCardView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.OrganizationSettingsCardView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.OrganizationSettingsCardView.html
  name: OrganizationSettingsCardView
  nameWithType: OrganizationSettingsCardView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.OrganizationSettingsCardView
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.OriginSettingsCardView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.OriginSettingsCardView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.OriginSettingsCardView.html
  name: OriginSettingsCardView
  nameWithType: OriginSettingsCardView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.OriginSettingsCardView
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TaxatorSettingsCardView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TaxatorSettingsCardView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TaxatorSettingsCardView.html
  name: TaxatorSettingsCardView
  nameWithType: TaxatorSettingsCardView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TaxatorSettingsCardView
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TreeSpeciesSettingsCardView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TreeSpeciesSettingsCardView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TreeSpeciesSettingsCardView.html
  name: TreeSpeciesSettingsCardView
  nameWithType: TreeSpeciesSettingsCardView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TreeSpeciesSettingsCardView
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TreeSpeciesTypeSettingsCardView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TreeSpeciesTypeSettingsCardView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TreeSpeciesTypeSettingsCardView.html
  name: TreeSpeciesTypeSettingsCardView
  nameWithType: TreeSpeciesTypeSettingsCardView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.TreeSpeciesTypeSettingsCardView
- uid: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.UnitMeasureSettingsCardView
  commentId: T:ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.UnitMeasureSettingsCardView
  href: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.UnitMeasureSettingsCardView.html
  name: UnitMeasureSettingsCardView
  nameWithType: UnitMeasureSettingsCardView
  fullName: ParmaGIS.WPF.Modules.Parma.UI.Addons.ObjectExplorer.Cards.Views.CatalogSettings.UnitMeasureSettingsCardView
